#!/usr/bin/env python3

import json
import sys
from hashlib import sha384
from base64 import b64encode
from urllib.request import urlopen

# gives us existing SASS_VERSIONS so we don't need to refetch
import versions

json_path = sys.argv[1]
output_path = sys.argv[2]
data = json.load(open(json_path, "rb"))


def calculate_sha384_base64(url):
    # Calculate the SHA-384 hash
    sha384_hash = sha384(urlopen(url).read()).digest()

    # Encode the hash in base64 format
    base64_encoded_hash = b64encode(sha384_hash)

    # Return the base64 encoded hash as a string
    return "sha384-" + base64_encoded_hash.decode("utf-8")


def name_to_platform(name):
    if 'macos-x64' in name:
        return "x86_64-apple-darwin"
    elif 'macos-arm64' in name:
        return "aarch64-apple-darwin"
    elif "linux-x64" in name:
        return "x86_64-unknown-linux"
    elif "linux-arm64" in name:
        return "aarch64-unknown-linux"
    elif "linux-arm" in name:
        return "aarch32-unknown-linux"
    elif "linux-ia32" in name:
        return "i386-unknown-linux"
    elif "windows-x64" in name:
        return "x86_64-pc-windows"
    elif "windows-ia32" in name:
        return "i386-pc-windows"
    else:
        return None
        # raise ValueError(f"I don't know what plaform {name} belongs to!")


def format_starlark(value, indent=0):
    """Format nested dicts and strings as Starlark.

    The output uses trailing commas, so buildifier does not change it. This
    keeps the generated versions.bzl stable under the buildifier CI check.
    """
    pad = " " * indent
    child_pad = " " * (indent + 4)
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = ["{"]
        for key, child in value.items():
            lines.append(
                "%s%s: %s,"
                % (child_pad, json.dumps(key), format_starlark(child, indent + 4))
            )
        lines.append(pad + "}")
        return "\n".join(lines)
    if isinstance(value, str):
        return json.dumps(value)
    raise TypeError("cannot format %r as Starlark" % (value,))


res = {}

for version, assets in filter(lambda tup: tup[0] not in versions.SASS_VERSIONS, data.items()):
    res[version] = {}
    for name, url in assets.items():
        platform = name_to_platform(name)
        if not platform:
            continue

        if platform in res[version] or "musl" in name:
            print(f"Skipping {name} in v{version} because musl is borky")
            continue

        res[version][platform] = {
            "url": url,
            "checksum": calculate_sha384_base64(url),
        }

    print(f"Processed v{version}")

with open(output_path, "w") as output:
    output.write('''"""
This file is auto-generated by sass/private/genversions.py

The integrity hashes can be computed with
shasum -b -a 384 [downloaded file] | awk '{ print $1 }' | xxd -r -p | base64
"""

SASS_VERSIONS = ''')
    output.write(format_starlark(res | versions.SASS_VERSIONS))
    output.write("\n")
