
# This file is auto-generated by sass/private/gen_versions.py

# The integrity hashes can be computed with
# shasum -b -a 384 [downloaded file] | awk '{ print $1 }' | xxd -r -p | base64

SASS_VERSIONS = {
    "1.83.4": {
        "aarch32-unknown-linux": "sha384-AI9mhDFXE09//hhOZ0fFpi73lXsiTk0od0sNUiYYpgngN8lv97XPE9Un2ruduylF",
        "aarch64-unknown-linux": "sha384-uf/N+W6/YXKsPTmVVq3w6mpLVUMcVyhwgBbwqm9TWdMLm9vwG5HRyBUzT5kVa0DG",
        "i386-unknown-linux": "sha384-UyGLyUj/QP/HUl5jdtJwi9S0YuBQpJaA+w78zoLLY/Xk2EU7lWG80oybit1sfCr8",
        "x86_64-unknown-linux": "sha384-1ds/1oVRs10Tvp2nuh8p2jf7LEQsScmpPVU+ElEHekJQhz0JwAIErZC3a33rSdsZ",
        "aarch64-apple-darwin": "sha384-fKVeDthmVP7veJ4O1rk2tdK1dGl6Ge1NPpAe7NYlUr0B6Fth5IQOjocLSBPE8E0V",
        "x86_64-apple-darwin": "sha384-jQR3LdAxF1xD/qEZzocctSK5YQ0pTXg2bVacgFwzOfXxLXOahfIz4qrA4Oqc1AjJ",
        "i386-pc-windows": "sha384-J7jUJ2iw9/MO0Q6i7PvgoMhwaSi3mK5Coxn0Rfk1q8Usyqzhuizj7IGUcMhyknIh",
        "x86_64-pc-windows": "sha384-TEKNYCiZctznLpswkACxP2Kf/ucud3ypu6J0foHs2Z/OgkqfDQuaiRHLuEhnC0hu"
    },
    "1.83.3": {
        "aarch32-unknown-linux": "sha384-gzCyG0fVZYmzcWRGdnBhMG8hLrT0XiLiLy7dPSlM4Mxs7cxnfFlXCNxQKTg3inux",
        "aarch64-unknown-linux": "sha384-Lsv2FdfzV4imNnFOC0hBfBsTzmox9Wf7NAh/EOmBnabS+jiygN+uppz8do3OQaTr",
        "i386-unknown-linux": "sha384-R0YdjN2HIjDuFThYSeBg//ecO6C7NtPh1jpeEfLucVIDPmMtsXLLOl2nhnt4n302",
        "x86_64-unknown-linux": "sha384-zpQKuDoqKEccwUCui1dmUckjgdtVW0rHyRvCqDTB2ulhO+9O0zBpPHWS9bBpWi0j",
        "aarch64-apple-darwin": "sha384-8azsIh3lQreAwtwkBLFipLSZ5U9f3NcVSoAsLD5TXI/RwFinfTjQ8PSHWM+/2ZyQ",
        "x86_64-apple-darwin": "sha384-ItQRuK5NFVWKKxTACXmFs80wXhKAUkey628oWdh8a8IOCsBfOvCPDtZjVwqGLdK0",
        "i386-pc-windows": "sha384-tIfHiM1nLIxMmiyJmKD2e5IQSFbWsiNpBFUoP4TjFBDl0DabdfCKhRAnfjfcBCOY",
        "x86_64-pc-windows": "sha384-1lBBH6JYm7aB/r8enP0t4TrAzfwzHR1K/a/DBjsK09ZEsbnADX8sZi/gSNNLL1Vv"
    },
    "1.83.2": {
        "aarch32-unknown-linux": "sha384-ZYAhJt2NWuZrWDcKTipWMOlg2KyILMNKYjYPNMbbiRIewYVjjCY2tqY3S8Di8L2+",
        "aarch64-unknown-linux": "sha384-1bmp4SMO5pwIgymP3qm+kDu9hzc8hEvvJUohPPpx5lGNSU7HAE4QKOtYjgVrDMMR",
        "i386-unknown-linux": "sha384-z1xVi02yz0nwT3d6XQNuUAx3AjyLKYvxvQzkNx1Erhwrfv+W6BOOFKfaqLjOSPi0",
        "x86_64-unknown-linux": "sha384-npHWSNwcTX1Aj6GVk3y9AQUrxgKzNHdlLf1ri/lGjqeF1KolUb7b92LP9U+puYB9",
        "aarch64-apple-darwin": "sha384-tOYwtqESBrHvcvHXuwRaT2vOEWjBZV701MqPUcvNuNrLuoHS+jyBa6OYx8gk311y",
        "x86_64-apple-darwin": "sha384-IRneWfykjAvkdjeHlhgR/tV1PFQVk4RelVZd6Bm+N3ISWHPczHQUserlwN9DsIHL",
        "i386-pc-windows": "sha384-NqDrc0I/yy3XUOs1ADxbwZB3+PAQWVjU+ULOxOWanS9ziNxPlu0yHyvtuKXFYAMi",
        "x86_64-pc-windows": "sha384-UBHkt26spZQa/cGK4fmcsjhHIVxFy0Xrexmmt+aAYr5ayC1xgjRnujELN+9OBQnY"
    },
    "1.83.1": {
        "aarch32-unknown-linux": "sha384-SKG0knXwDTjD18YDwJO1VhLmYA7+Jawemc3qFPCKMJB5fYqumwmQdMQxudNuFYUD",
        "aarch64-unknown-linux": "sha384-EijxFwBHNI5cXWaoOynTrb3zG4QBR33N7xeBKpoUQ9Bmwn6qQCoKbi6+2Tuu5Kzr",
        "i386-unknown-linux": "sha384-HHOZh6zPjvxPUN8mOp/wZLOnM2L2reFP7f6EqATfw3det+4Bg/Xay7KrmZaEoGGk",
        "x86_64-unknown-linux": "sha384-owxzTz6Nej0Btfd/AXe9yLIDswajmksajTKDM/qFTBP99TFOb5JOVN1vMdwKdEb+",
        "aarch64-apple-darwin": "sha384-CLm+GcsxerFiYATuHuIh3zECi4NOmYAUYpUpZx5g7G8UtPTxKi+26F8iGtwuXSm3",
        "x86_64-apple-darwin": "sha384-lhK47G6Ecn2rSxqP+QiGn710He2SzfBmxJ1vNxias7qBv1s5Kz7cGQz7RyXxAfLA",
        "i386-pc-windows": "sha384-tbC9kzje3Fc357BMCqJGrhG0IM6OEfsqOoToblU5fxESWxgKltPsle9Itl9I0l2H",
        "x86_64-pc-windows": "sha384-+N9L/l4OuMziytHNbWS+iPyH+teOo5ISKmE7QSkg5z9MWCmi89/rVdz/naJYI0nj"
    },
    "1.83.0": {
        "aarch32-unknown-linux": "sha384-GZJjNlHLGySNnbm5yJpdbyejip5j67BpH8dXMFn47gf/1VH7FBZ9o6scFQnxFbW1",
        "aarch64-unknown-linux": "sha384-mh/CaWEW+Xj6nboef12YNaG9cQA6GxFq2LcRgb8RK9dnZO1k/S17jZEWjxnmQ1XW",
        "i386-unknown-linux": "sha384-ubFIVGBlpZLrzW70fHlC/+v5wMrrvsepuXMaAnegsQ9nPlaSKJcAnMv6j3IyJOsV",
        "x86_64-unknown-linux": "sha384-MKRJxPDb8Wf1zrU6CI2tGampGCT9/4UKiqVpTO6p3hwTU9i0ZXPosT911XlPlRFB",
        "aarch64-apple-darwin": "sha384-qhlnCncSUqrrJsQgAKGU6Z7KqJwaqjrQBrHfkssrDRQWW8qt7/LxeReMFs+5rhJV",
        "x86_64-apple-darwin": "sha384-LSL7J9nykFyoJV9Wevl+NMv2ubIrNClKTsUSTz2oaxm2jZ+aYbxk2PZ6xZEDBGkx",
        "i386-pc-windows": "sha384-LUOI5N+37b5BPfkU5YpuhpVkIQQ2iqagMTGT1ExEp68ocXw979xKkiNgFZtullwf",
        "x86_64-pc-windows": "sha384-VitYde2ZU42Fw9O9xB638LX/N77fwOpinbgvf9r8Sd6Ot+qkwpEvftgSTkZEaWaF"
    },
    "1.82.0": {
        "aarch32-unknown-linux": "sha384-1kI7h1Qd4GOeWVR518UCTzG5HofQP3DFngU/rr0xDpMnSLnWtqEr+eoxJ9r6aHb4",
        "aarch64-unknown-linux": "sha384-Ip3jLbwCz3Anf1I6nPuWgSwxsjMDpKxUvUNIgKYvViNsioYlL+83bCiohW7+bLUF",
        "i386-unknown-linux": "sha384-zWB5iqfHClKMicJJZSBGZho1SvsiFrrW7u4FlBxr6LVzR4HdmFoTEmNLH7SfaMc1",
        "x86_64-unknown-linux": "sha384-2kdA3Ha50K/QQyZYrIdyan74yAoe8WR5AsbYSemUcFAb6Yf+O8cdH5hHyGrT08V6",
        "aarch64-apple-darwin": "sha384-s00Ndpc4llaBJG2idxXvEE+K61sA4/LhFF1yEM//ro7Ptz+2iGYOLYWE+vL1+wO1",
        "x86_64-apple-darwin": "sha384-kB8XVlRJOzvYg4zTGT3xVLtrgnasC8RaU6x8gx3SEPyfq2petTtdKU6Y0+olppNz",
        "i386-pc-windows": "sha384-tFslU1J4gO1GCxLx7AiSM9uDzPVTHvEQ0WTFTu9szkDpuUiYpbqCqyp8RHjY777h",
        "x86_64-pc-windows": "sha384-oL60YgVHUqnGBllYGljc2z4ZW3B9OnfHRWFLiMg0rPF8MY0OG7GOhsmRzDIisx25"
    },
    "1.81.1": {
        "aarch32-unknown-linux": "sha384-Te28GkCms+cE0a1QMv8J30Q2jiJ4VBw0zdKNl5C/STiEKVLImYqmy99uaZ8/83wL",
        "aarch64-unknown-linux": "sha384-SIK6e/MYPkEYoNwZFNbxdAKf0Dv7mlYRK6wVXK9gqTN3AF4kERekz+JoPTDUQbR+",
        "i386-unknown-linux": "sha384-Mj+L306sGEnUrYaklz4n/VDYn1kZGsZH1Z89S9XEZfxQHf1dW0MeMUGs4r9VeLYr",
        "x86_64-unknown-linux": "sha384-hOrOxI8fJ8tFnnV02dFFPZY3MQV3VTWhXjn4zYxOXKNLL7vy7INiEoivKpH0Z5j8",
        "aarch64-apple-darwin": "sha384-tASQOzR0k4/YiXKRjEjd4wFG/SDsqMfijkOqjohdZyx0MZx5HUPQQCLcPgd602hw",
        "x86_64-apple-darwin": "sha384-a2tWz1NCc6d+Kp1y9u0QJfH5IeqqZxZdhrlp3Z5sD/wQkwXggpZ6qrhvLI2g8fc4",
        "i386-pc-windows": "sha384-FWfM8nEnkWoPoR6Stah1aI7g1L8GriYqbneqOPWtyPM1Xc0xOWn7E7s3RaeKhA9N",
        "x86_64-pc-windows": "sha384-JmAMZTo4hUQLEESXobTEf0apCd6WatOMKCEO+z+iLaJ+QOGt60RunJy8IHI46rBr"
    },
    "1.81.0": {
        "aarch32-unknown-linux": "sha384-XoKdqohMqYopNSGcuFBJZ8pwIGTvS4ViMKRpKPdLigo1BTcC8Hanv3fHGliQTkgP",
        "aarch64-unknown-linux": "sha384-9srMmPZh56BRA7b0WbHaLqLgL+SdGYpjKOfF7EqdF6vc46fQGTSMDG5/3IUjeKS0",
        "i386-unknown-linux": "sha384-ujCMPfqwJbbJHAZ1/vtZGAj7ekdX3DG45wO6XZCvDxxEBgQUG3o04eUvnpS3kASt",
        "x86_64-unknown-linux": "sha384-Wh0LORdOM9Ajpg2fuzEDapbXKvq1pyycKgbwdZCZ/FlCYJTk9a8FDVl0lHJWwJ4Z",
        "aarch64-apple-darwin": "sha384-BdiiYPrarz7edBuzBiNF37LMxl3cMLy6I3Bgn/XQKQw2bVEFtKqotEerLvBOWXlR",
        "x86_64-apple-darwin": "sha384-Dw40xlSmzqFDTJgumhHemMh9XtN9tuI9Aa0X0qknIHjxz1xDb8h9VRIx50iZR0BX",
        "i386-pc-windows": "sha384-eNEe5kU4L03mZpBao+iI32xPd2JmbRn0vNiBH8HwoxLDDm09Z45p7u/oIg1mun6Q",
        "x86_64-pc-windows": "sha384-ARa6Wb16gviUMkkQNSOPsN3CuVpvdGsxb7ewQrLVsRhPEZ6f741wRThj1XdHgwFm"
    },
    "1.80.7": {
        "aarch32-unknown-linux": "sha384-lWhjB1QyqkX31wyiX9u4PNmfsM8e3HzyGrob3YcmVqo3eszHKBM3U23feFh8jVql",
        "aarch64-unknown-linux": "sha384-/LPDFu5W5VyqXaSLWsuKfV1ccPRoZte9TxlbO+RloO66Uz2osCUdcfLZFmRJ/Qg3",
        "i386-unknown-linux": "sha384-YirjsEMR1hwInQ15HNh5O+H89fIM0bgmleFwFhIwQWNksFe8diqKdYFecwmBW4Jf",
        "x86_64-unknown-linux": "sha384-IJaALP1QkJ7JZnSDlssOzxPMFuBQAcOaFC6E9xq0qpvzjvHvVTuT11jBa4Kk7e79",
        "aarch64-apple-darwin": "sha384-O8L2IQdpUdwvyz0uXuLGqb70Dm27jojCpl8QdSQdWgrouoXToCCTYlDIbCSfvCGV",
        "x86_64-apple-darwin": "sha384-zqB1VWrTVuvnd7WiDNekIaymUcjcnvIv1lwJsvZEBVD93V1uzWSXMsBPsCDSfS0C",
        "i386-pc-windows": "sha384-x+vhkF1UugEOpQ4ts4CBuOoCDcsTfmgqJK/TJTlfQ2NZnBkAuONqHalmX8RaSznR",
        "x86_64-pc-windows": "sha384-V+FQxrptCRJx1X2J1QW1Vm8TDtT2avlC2U8OFqO+P9ursqCYEmrzAIDoBDDGy+fK"
    },
    "1.80.6": {
        "aarch32-unknown-linux": "sha384-nkFHLoWj+M7zuGMLMobccJf3R27tKIgACQoddEOVEEXaKbyYbvUsHq6LqduYyuxl",
        "aarch64-unknown-linux": "sha384-WwQVXS6MdKqnqLMIPgM5bIxRWhkM/s7YJEH3uuXS7QVAFDlHneZVqEh1tg3LEn10",
        "i386-unknown-linux": "sha384-q8MhmdE8fvcbnrKwyok6BoMsGDPzR8YzQeyJYOlODbHtElBCT47EJR42R1Dyp8Eg",
        "x86_64-unknown-linux": "sha384-x71xuNupvZO9oW60RSFx//Hy64PsdH17Hkdg6PT7iV01KgdB0anfx/RfN04c1Rf5",
        "aarch64-apple-darwin": "sha384-gA3LxX+D2Dm0Np3VWjOjB0v1FZQPIzPUvgXjPTchko2NYLskTXPDEaPO+1Nb8cXG",
        "x86_64-apple-darwin": "sha384-mVt6HX7zakCIPfMWn5PIHQsOm+hvLYpLi+lCRdhNIeh1Az920mhHsme2pGQcaoFn",
        "i386-pc-windows": "sha384-8ZUIqU609pkg651hUCXFAI72CDleEuRZw7HjqutLC2j6Q1jVF4BeZSiRXKEwc69A",
        "x86_64-pc-windows": "sha384-hsYKIQ9jXh3oBh0vSoB9HOY3YNjAP3q12lKOkrP4z6BY67zM16vf5lfGurZ9QnTc"
    },
    "1.80.5": {
        "aarch32-unknown-linux": "sha384-GyJ5k5Q7AYQIfDUavev0HwXGBKtyWRzD58ary+LS8LOMG/+l/lUy7o0eBRuZc/fu",
        "aarch64-unknown-linux": "sha384-Z9AJF4ht0/FaYG4sDA8NAql0EKQ9VC9ZVnExUIuqwuE0kVj9jm7b6mHcE5L1runf",
        "i386-unknown-linux": "sha384-kvv1zvVVNma+0iKekaSCPta9QGWH2FfDRU6YPr/+mNa2tIAXBOWc2itQ9PUmCXV3",
        "x86_64-unknown-linux": "sha384-goA/w/yo9ID/J6oQlURLlIypn1NGskb61PPK+Y11LtsvYSg7hDAk6WieyX1pyCU9",
        "aarch64-apple-darwin": "sha384-OmylApVRAGHJVrfOmoznhBaLyUho2zWWK2xI0eAI/DC+c71NoNS0vQaKl16XM5HA",
        "x86_64-apple-darwin": "sha384-mbgsToFHYQHYQfTrvsp4bYQht+DIp77k66Rc757TWH9LPc4b/mebCMP7iMpd0Dla",
        "i386-pc-windows": "sha384-kw9X3nHBZxBmkSOVuAxMr8V+lzpXWY0a5XwRzrlmi8NAjrtYFHf+e2y0XEo0+5EJ",
        "x86_64-pc-windows": "sha384-ApUGJTzb2aXVnhMQeKk7ZlKQfPYO8foxcEyOfQGeSuhZkZ64cZHeswkpR3N53spS"
    },
    "1.80.4": {
        "aarch32-unknown-linux": "sha384-xBlkuYKHpKmr19It/gN7EHwz/eKs+9XL7JsfMB0DHModNLiYFUizd6Kzp+B1V6WZ",
        "aarch64-unknown-linux": "sha384-+b+zRxPx1CWhiuA80IMdKH7+DJmZAlgtownkfKEWr+2yMkKwsH1c2i8FJVY59Wht",
        "i386-unknown-linux": "sha384-dlTlAeTMEY0Q75gO0je05FQos0ix9DBb8/1kOaDH2iSipUDX5mxjsv9yIKqNQS9I",
        "x86_64-unknown-linux": "sha384-h4uMpEg/khtALWUxmJI8LUF442pUqB9R8/HwH1kIU5jQ3iuFhp0yQrfV6tQaYOyu",
        "aarch64-apple-darwin": "sha384-ZCbSwb/RqmbawCSNjifeT2YdtAPsHbNgFJ3uA9s7GY9HyMEPLDo9CbovLiYVxaF/",
        "x86_64-apple-darwin": "sha384-5SZsL719MV8pK5FAVzyTFbz1ZpxyYKsQ6G+l8NWKdcYG83Eljh4y5GOquqQULSxZ",
        "i386-pc-windows": "sha384-VDNTCxom/9N9gb4/a0FhQWkNSsyuaRb7V2UIMrHuxiZdmtKGe4qLNO8sAFR9sUiK",
        "x86_64-pc-windows": "sha384-Sfk8ouh+iT+6eN4mW6vFQ2+3V1nlXQrA4L/sfis18VE6iRsFAeNArOrxZHz5LnJY"
    },
    "1.80.3": {
        "aarch32-unknown-linux": "sha384-jq/3tgTCz6p2hVT35yq61bxfoqWL64SSY+HY5NE61Za7Sukh0Oe488jojwSPnEkX",
        "aarch64-unknown-linux": "sha384-h/SgkDOwQ0kF3R444RUMDOCb5S3R0SdyS9pV7Ai6YXF3byF0NSNXoUGMmCUQQM4m",
        "i386-unknown-linux": "sha384-no6TPoa5vbKvkQB+bnmkM1FT6nFkOJ894789NnMpV70wyxnc0LpKipNbj2TBfHOL",
        "x86_64-unknown-linux": "sha384-8U0uYr75LpOthVfWw+rfS+j8xZ4XE1jZerlZZOw3nk8YZGihg5/giqRa9ui5cKqS",
        "aarch64-apple-darwin": "sha384-9g6BUHDrNHwv4Vw1uOw0twjedAHIVkOpoQADoqoqRJGun7k+rB6l7fgeLRaSzGRX",
        "x86_64-apple-darwin": "sha384-9KjsfypuW9nvFIOdPUFqucuZNGQ+WqH+WT9EbSey9ukUQQ7TeqEE9SOodBu3i9YG",
        "i386-pc-windows": "sha384-g12wtKVnHvjU6vvuhXC6T+ZojGIiX2zp1kD4akw+g1Jm16Gw+Z041wsXlqCgbAUh",
        "x86_64-pc-windows": "sha384-DUrGhXUMXsRfclsupOhVGkO+ieuWDZ5PuGJf0Ooy/HNtuq3P8qCY5qEGVuuLMrDk"
    },
    "1.80.2": {
        "aarch32-unknown-linux": "sha384-53MEfX9f436p+nFycz6u5IYLp3dbf0vEW+sat6JMOUFhiWBw7JS66hGJjY+xeGke",
        "aarch64-unknown-linux": "sha384-U0fCUKLxVURUs7/KTUXCOVCes3b2GgjpGLvTLV4L09icDDhfxsMWcWqLGd3px6Hf",
        "i386-unknown-linux": "sha384-doA/uRujUE6vooSpSgmFquywnhYJ4mmPh24/geYmvgv6d/1iAqilAcvA9vz2bsP/",
        "x86_64-unknown-linux": "sha384-lUYhlSNSgSklwBUWbVU2APKBJPDnXnMyAwhVG19gLfwzZ1WDdjVkaU0DY/yfn6qW",
        "aarch64-apple-darwin": "sha384-AiGRg7w/fzLneeGv3QO4you3dAuLHgBPSsR7JMC8TLs83uSy/dfF6ERIeMgv1pli",
        "x86_64-apple-darwin": "sha384-uFNBhhD3DBfGozXFrfuLxxEo2cscxkPaVrUaALczwZIvtivnu3mm+SkZguQL42By",
        "i386-pc-windows": "sha384-IaMuRsuR969aOy32U85KKyHR4RfWX1JMU58NktZ79XxeyMsErfKiQT1iD8nYyShz",
        "x86_64-pc-windows": "sha384-Uaa5ulCvm6htvnl7UXfABp461XGRhr4YP5yPwoFVV4dFEn09Crbq90RrAnwXZlwz"
    },
    "1.80.1": {
        "aarch32-unknown-linux": "sha384-K5MFpd5VG5Vw54oAmNUp8k2k1h7de4w//u1F/uIFX8dQpzA3BRxePg/Pr2ff6wLs",
        "aarch64-unknown-linux": "sha384-F2mERz6MFhfHhfMQpYuOKhvJAog6pnvAzTYXo/7EXVKrpCjesR90exgqr2idS6ZB",
        "i386-unknown-linux": "sha384-yeszg9g3X9FZ7hyv9NOy0DyJ798aFdbLSOYErXnA5A7xVieyjJ5g+UfsDSRpor6U",
        "x86_64-unknown-linux": "sha384-D3se2l+CBzh0MyRc/TKuQSnXGsOPnZcyFsgk5+reSvADOT38W4KrphW77IAahcJl",
        "aarch64-apple-darwin": "sha384-mAsE2psO2jGVNHYpOCtvY2wsoV+l2ZGWkpmMy5479lShUDqj19X7Uo1USGQWsAND",
        "x86_64-apple-darwin": "sha384-lMbOnzPL8ooOTwtweUjlHeGt005QNGJbM5ysw+dlEq9aOdlYCQT++8xdGXBdODM8",
        "i386-pc-windows": "sha384-3zz9vg+ce7kdUC199o0eOabHD/PKaefjrrwRnbWT1SX86rn8nkIOII2Jpxwyia98",
        "x86_64-pc-windows": "sha384-aA9vhvZl7nbj7FuX1LVeXbtpQbLbowx4z9kL7abItgF9xN0iLn/NOJQ9g9rJZ24c"
    },
    "1.80.0": {
        "aarch32-unknown-linux": "sha384-NWWJjtkGZO47zI3frUsHlr3trzgnwU7NGzouuNkDxnB2HcZuU4h3O4IDETNfBA8U",
        "aarch64-unknown-linux": "sha384-/83ydsgvV22AdPc8kWabVsBS2rLYt3JVIAfauSOgBsPUl1ScTME5OTelJ7L+nUWv",
        "i386-unknown-linux": "sha384-dvLibr8hHzsl/C8/dDVybsb0Efh5uPr+9fS/ffW1PCbunLvNnTEQGr4SuBMszdYv",
        "x86_64-unknown-linux": "sha384-c36l2wxsYtBqQJSO0MZ/LiLTAqRFMLIqXGqahzk+N9XoAUVRP5BxtpFrEvCzoYol",
        "aarch64-apple-darwin": "sha384-Zh52kaASpscIMb1SavkU9SSCzQyJ3MIq6P5uNAmOTFLwfq9gdxat36h6wN7LvpzG",
        "x86_64-apple-darwin": "sha384-CdWGqzuAqs8f4XUzEEQH1Z3ck7goKXTXnt7PUswTci4PT13ebuSClGwcbzwZlzIQ",
        "i386-pc-windows": "sha384-+8ShYyJE2oVCRjb+5qWjT/8fyZ4M3EyGBSDRm2HBlHKXPYHUMwkNcYTWVFt2oY9Z",
        "x86_64-pc-windows": "sha384-UzoIWrmVBGdbYL/t/g2jd6NmSmMzsyk7AB/RxaSggWpd1aDfqfXUN3+bf+f2ur2r"
    },
    "1.79.6": {
        "aarch32-unknown-linux": "sha384-NcNItopJ+DG9bwk/Xz3VwgtsfMLwKCHxCZqx26+DzMK05L4NmQGQ2+88mNDdzvi1",
        "aarch64-unknown-linux": "sha384-TNAOniNQxbbe5FSm5bE21PiqKspY++cnjetnE3NxBEhm0rygNk3NTdK8XcdE09Cn",
        "i386-unknown-linux": "sha384-pp1aayFs1kF0peqHuWtq2JHKBwqlLaCD84YcBUbaIAP+jxx8CdQ1MA1MU/k/dlM2",
        "x86_64-unknown-linux": "sha384-65xYLZFwskbyg0befeDEtApqRXCmN/bbVs65ExinJMbnrldy2a2fNsTlHQq+c+1/",
        "aarch64-apple-darwin": "sha384-R3ZEev50/duNZv1Sp4a1Fp4cQJqcd9k7wVc7oBQcOdN5tZovgciGrdEU8ZeIGuh9",
        "x86_64-apple-darwin": "sha384-PilK8n8RBjIpWlifmW4Z6fFgXNweGx1MWSKuXrt71yEOsXxaK9Quk8WDa+klhzWL",
        "i386-pc-windows": "sha384-DQXjeYH0QfUwzVodkrUraEifBVBaZMMeFykqA+Gp+JcXFwntUNcd/TuQ31NBNAuu",
        "x86_64-pc-windows": "sha384-niGorqpwTdzhQSz7bU3Ym+qiDG6XZch8ovLWFfwMjKPPU/ZlJc43bUVE7W4gSyTu"
    },
    "1.79.5": {
        "aarch32-unknown-linux": "sha384-PJX5wOgCRlwWkBMrylO/1jkVQqyc0VJA8thxcfvuR6rWwkfZ4Z2MggONxZO/YJru",
        "aarch64-unknown-linux": "sha384-5ZDq91n1jVgxbLmknvdfDTjo4+fnrUbiTEETyflpts41pq+D5FbI2qM/Z9Mod4sG",
        "i386-unknown-linux": "sha384-dCjun/wCa84t+sDx8+v6Vyae2VCO2UAFNodKpJE9BWAM3L6oM248UJIfxzFeyAzI",
        "x86_64-unknown-linux": "sha384-Pit8KKuBK3GZYlfPHmmmBsuCkOctvdXo71CYSjAzJ01OvVLD1xSj9AQ6l5y8ksyS",
        "aarch64-apple-darwin": "sha384-rkmMp6OINzd9gBkRObrHAzLlJoW5zQ38McXlnH59Tj1MWeZzHd4520y23TOQiR40",
        "x86_64-apple-darwin": "sha384-fTYZTORuSa054H/mbKe5ntdI1cgmJTOW1lCDnupy58jkD2yMS/E/I5CvFN9UiDqz",
        "i386-pc-windows": "sha384-dKwWfFzWOjYczy2LfhTAWAPM7VnPLB4gI8nSgf54Y2M1nvQBYe/zEoDyOB6P7dil",
        "x86_64-pc-windows": "sha384-NpxrXEDFSMtg11l26arQsJqG3FTUxRUUth689Bx3NZGPoRxh5eWtz+73FKlxCLi2"
    },
    "1.79.4": {
        "aarch32-unknown-linux": "sha384-uEhML2vDMV/xrlLLZRsq0ebxO9TOjdyQiTpYGOAMK2knJkUlNSvz7dx/rXYK2b74",
        "aarch64-unknown-linux": "sha384-nql+YTg0uYMgbEtSbak9VGOlhsW/s2lSxRmNPSB7Azq0ESrDy4PfvLHU8US6Jsky",
        "i386-unknown-linux": "sha384-Pl4juDypA32AjQ9U/YUaDzpz20Mpp0BAD9DRQEvZx1tj+M8Do8MVLfKPmuL5K3sd",
        "x86_64-unknown-linux": "sha384-jzLnQ6VvIp67aF7wkWw62hqqzyM2ODhdmJFU5zWLz8/fK/Gobw0EIwWmom/cb0fF",
        "aarch64-apple-darwin": "sha384-H0rMBMBAsVEe2CnFULbJDWuU9R6BET44F2MsU1QZGH8Bie3wmxWdHe9Q308rL+AH",
        "x86_64-apple-darwin": "sha384-Sw7ReZ1b2+YMALZ41G1mAgc50k+GuVBvoB2xXGGdEpFofhU9DTt4RB+bPQCAiJd2",
        "i386-pc-windows": "sha384-1vw7zKSrp98p6C9jWTgWL7klwTPu36rXy6ho+3S4GsJxLm/Q+vjQaWuB93cfj7sK",
        "x86_64-pc-windows": "sha384-Ty4v9xq7Dq7CpS/Ly2IfU19v3zWa7l5prdHXao2AZqCF3spqbS8CmaAFuqJirU9R"
    },
    "1.79.3": {
        "aarch32-unknown-linux": "sha384-cc26Cww2v+xYIRMJ9f5qLY1db1wwuXAD4Wu3IYwbk5xbcRin/7EpZIMkOsdmDnqh",
        "aarch64-unknown-linux": "sha384-up0nMjtNWAKpc6Gf2etyBM7tiG83oO7d5wPt+NCKlP6tEtitN62PrRVDf0wOMFte",
        "i386-unknown-linux": "sha384-6yLLa3dyIN41xcUrc/lqdCNsAQN6JesOkrCMdTKWwkiYNT93rI87I2BYu834WWsb",
        "x86_64-unknown-linux": "sha384-YmZNPBdpxsAiR82o5x8gvZdGtmFGv6xWg9TK4NhSJ3CDw8j1wcq32Ykif3/txMJP",
        "aarch64-apple-darwin": "sha384-88Ic5Tv2EhM90c7bOX/oQvXkzIiNZDyW/JVmstPaiI9D7jksim3f9qdcj3GQSHDL",
        "x86_64-apple-darwin": "sha384-jjHnA+/HIJzPO2QCkwfWQ/F36e9gTSRb1QWLQsRxgCk01FlJRxkER9iW367aRgLC",
        "i386-pc-windows": "sha384-WARvftZopYsMmKw6kMaDKNbWqv8P2LlX0wZVyCjrM/jR3G522A81R95bDQ0/1iW+",
        "x86_64-pc-windows": "sha384-1FV2QKbxFC5Ge30j/6RbH5VC1lOIBbJTZot5O+NNow+zSxobDfIrmB8XC7WeZl+r"
    },
    "1.79.2": {
        "aarch32-unknown-linux": "sha384-Cw5ghl7oVF/k/QkVxZrPi3EHzTS/Po1TI0OCq1q6rEqDLsuAVIQ2yQCTYRVumwFA",
        "aarch64-unknown-linux": "sha384-0yhOnKRhNmC4XqG62C3XzI7SahMRNvOip7qL6JspKz0NIvg55kzT/goKLgt73t9R",
        "i386-unknown-linux": "sha384-KG6G7j+MOOlmD92TUNxh/lI+iTW2Y1wvQkAX5q9l3KZfhGz2qn4G5pioi4PTIZyR",
        "x86_64-unknown-linux": "sha384-K9vzH+w7IFhdD38mmWrdHdYC97Wp5lY6bfBPH/m4ePPzGvMKJM8ftV6cpoy4auKp",
        "aarch64-apple-darwin": "sha384-hyejhePo/02CK0d5mAYk4ouqb4oGwMgm+yhzut9Cp0FCYDYEsyUAUKk3UsGxbdhV",
        "x86_64-apple-darwin": "sha384-hoPSpftcZU10Flrw5hKuqQCxfwtJqNHRuGVHGoVYXR13z/OMQZZgJRlSk50q8DJL",
        "i386-pc-windows": "sha384-QqV+FNwOlMoSpFi7YymaIpk2ruNP33TO43YYSiwM2E2LmYBpkHUHt07geYXqLlrw",
        "x86_64-pc-windows": "sha384-wjjPu9omK6Pw4EHN9B+Ae7RQREGSxYbKF2LG/W7SZx6OTP/lML+62r3eZG3bFEVW"
    },
    "1.79.1": {
        "aarch32-unknown-linux": "sha384-ALyyqnrdyKaS2ZbkrrJS7A3zRmZN5xjJV8XvGOciNY64AmHLIkC/vtvnwBJl3Sq5",
        "aarch64-unknown-linux": "sha384-mQY0W2SOg5YswcygqrhjQGfj1JMIQuLQZcxJNs+TcORaooY99jCiw7eNOEhTWjc4",
        "i386-unknown-linux": "sha384-0hx0wmi2WQwRzMwZXei2A3qjA7Y2yCN/55XmgbxF/P02SleJ/3vHDcxqezGgzcud",
        "x86_64-unknown-linux": "sha384-Twt05kp9ft94rXPZHKK7W7M7z+MwcfYmOwGrbahujHaSmEZxPJFk4VIK1xxr+JsS",
        "aarch64-apple-darwin": "sha384-cfQ07i9yS4d9gFn5o5PnSvCFyPXFPS+Ykrmh4Lj6AbffMhVaEMr1XD23q+ce8QML",
        "x86_64-apple-darwin": "sha384-/WvWBDAzDkwHi1e8TlkHCAhawsnhv14CP74CNPZ0cQJu2dgMOxCJhaFRwGMvO7hh",
        "i386-pc-windows": "sha384-uiOqZ16d1LH8BLfMk7RtrOVU+X3KcUlprvtjrcTwd8bvEIxy/0AWZ90h/9EfkjJD",
        "x86_64-pc-windows": "sha384-zVVTGkY73zP4i2U0Dh8FLCEFZGmnKgRYkXZorRfE2AuE/IYQLZXIz2l4w5QyyOm9"
    },
    "1.78.0": {
        "aarch32-unknown-linux": "sha384-Gx5pxduosOv1VUxAB56CTUhyiiFdl+0I5S3XUhWRvFB1ZKy4TNTWYsj92H3kygNv",
        "aarch64-unknown-linux": "sha384-5Tjy33+hvEqGLovBh4vEnirNeSn8RRe5eHE0SpYC7P9JS1UBijYrnrATkPJ9E9Mw",
        "i386-unknown-linux": "sha384-UINDKTIdJIbXY4FrHjJwKNz26weln5AoFMBM5VneNbzRoFPOUYCQA+IlPwCm+Fs6",
        "x86_64-unknown-linux": "sha384-XlIinr4ibYB2UiVEYtoH7rtwFavdcNE7mMax5KYWgtGGVA15wSaoIc2JTptme4Xf",
        "aarch64-apple-darwin": "sha384-hOwR9iNSvTwhXP/ZrPMfzKqNJa6NOHykt01rWBLeNeDz611EwAccomnHHw2CiNd7",
        "x86_64-apple-darwin": "sha384-QDhgTudP70lEomjRVmpFOxiidVeuM/b/PcIw1gYSCRMSx0uTZ6f1rQ/SIC59oH8J",
        "i386-pc-windows": "sha384-i3lxK0HZBOzohPlwpIXnWdiCp924dimHu3LinDFLiINYoUEV1bf1R+0CA174/b+S",
        "x86_64-pc-windows": "sha384-B+JHjIikmVL7ZaJMYOyjCC54VSR+gaBDEB1PL5ra1b7Lk4/4pIq/qoaQf7xnTgjP"
    },
    "1.77.8": {
        "aarch32-unknown-linux": "sha384-cNEOqZwU2nOfGZjyMEAhRo/jHugVz0koe8lLF9TD6bCBvoIgUJ1rUfCC0TWy85tv",
        "aarch64-unknown-linux": "sha384-4N0qay631YYBfOG5oI0KH6BhD2UwFbimYq7J5q62OLoZqf9jbY5kLXLPgr2NM7bd",
        "i386-unknown-linux": "sha384-rKq56E5u9M2cBzCjrmZDEaEXEwRt6JLCd5sWnmRvV1W4JbvYn2T+4ljplhK6AhVM",
        "x86_64-unknown-linux": "sha384-1QigKNKbMl/aSrP3Tx4aHKH8KmUUiA/sLWgoOG8TyDXi9tiqpJR4Q33Ef/x7o8Zv",
        "aarch64-apple-darwin": "sha384-EXAZbk8TdEpSj0Q+kp6MjIPayN+nan9L4CP/6gc5RZuMNSNsbO6Fh6kmmfx5OJuh",
        "x86_64-apple-darwin": "sha384-TSQkGUqiCltb9e5j+p1nXFJq1A21e8Iq53bLJqxAyaVmYit9xy7C64jaGix8zZCa",
        "i386-pc-windows": "sha384-sxLQ8qgW64MwTOpe5MXcG1NWWvb6Dzix/XImbqZnTZIYm9lH4UH3TMPp4bUFUIAQ",
        "x86_64-pc-windows": "sha384-6RID1GYghWPVbyzSPNlSJDJUJvrtYdIheMahiDUcx4o2lTFuwSAL059DsGU55Fyk"
    },
    "1.77.5": {
        "aarch32-unknown-linux": "sha384-PgS2wPLCQ4A12OQ3wEYdAj7e8ZGz0dNwj4pe+3wSiht4ticsnoRjES1BRVXBfkVB",
        "aarch64-unknown-linux": "sha384-d8hsUCPVJYsM67NCafplgi4kMJZynSi12WLk/DTlm7b7mk+PP0crR7hBc0tgg3bK",
        "i386-unknown-linux": "sha384-OH3oNYGROiy1CTbKw5RCgQb/pExBars6eHV6R/jAwMxppWy8P1kvan24VRJsOprO",
        "x86_64-unknown-linux": "sha384-7sbo0AdS5RkfPEEPgMOCcFNJsc4sU/TBBRdR9KwmMuaXFZR9cBDY7VnJzgSrDrnE",
        "aarch64-apple-darwin": "sha384-sZeJ8aZksKVcJtd64I/Mqgt0Y98kvEB36MrkoJ2MLk7V8kJHhZjMi3nrzIl71bzR",
        "x86_64-apple-darwin": "sha384-AwNrR3zhEXQ7ofM957wa1q6HAYsZLmcfHurJVTFKBDA9LWlButXnexaoBmGhlN6A",
        "i386-pc-windows": "sha384-ymkWA4d1ReKUKKEJylfZ4JxSXyZUgahXcqVMrLEJ4F4b9GLlNWESA2rgqfqVRBz4",
        "x86_64-pc-windows": "sha384-odcjq6f5lHysEEI/LU7WyhYF4cnqdvZUo+weegK7eeOkN2semtPbsZQEviPerRY7"
    },
    "1.77.4": {
        "aarch32-unknown-linux": "sha384-hNu9nEiyQRir0EAHV1Yg+8ncZn4mLOW5pGVe63bX/0yB1s2r0thxXji2bIyC2j7H",
        "aarch64-unknown-linux": "sha384-FI8rzhKn9eNfhbSWHYhkNSXIEx8rDMSWdCFRqlyCfFWQzug24ULuUFmw2csba27W",
        "i386-unknown-linux": "sha384-1l3DTsy2UTc+4X6Kx2xJgzsr3jJi0FdjjZSgH66HIrLS5CB+001lt9sVDXvFxhg7",
        "x86_64-unknown-linux": "sha384-X4Clei0MSyhTLtUyeSgKpg6qvTC+Fcno/MpFAEcOwT6DUUznU3M/jJ1A6Pydkx9W",
        "aarch64-apple-darwin": "sha384-Rowy7rTz6BQ4z102eZKAnXMBFZMX8N/KlsPzVrW3KWIntxx5UGy37+bpZJ3p/WNU",
        "x86_64-apple-darwin": "sha384-JAHZZ1pnm+X/Eze3HYXutzg4raqs3kzQeeQMMRU83t7z+khRttGTzRNbTYRsWAw0",
        "i386-pc-windows": "sha384-ybq6PW4yCEyWWnOAdXu+6WpjaN1ZCoFh1H8hBiL6ooG+4li8GLIZsmUIu7NLRgOH",
        "x86_64-pc-windows": "sha384-DSIzRUvw7a1zLbKDX/RxoEwjzs3l70M1hRXw8dYDerXp+croTSdPs+5tNGMi9uoI"
    },
    "1.77.3": {
        "aarch32-unknown-linux": "sha384-ZZBujhtrP0WJyAiQGGgutzvIaoZCL1a9NEpHhPybkp1Df7o6z8LEJ4mIK5wM6GW7",
        "aarch64-unknown-linux": "sha384-7aanYvgWabxLmelNziOLrd7J61COqw3XwmkJMD9ZfbVBzovXD9L8ygp//8AUCqrr",
        "i386-unknown-linux": "sha384-gahQQHY6nEChjWJ/3YRt4YEz7srBIHiBBkzb1tNx/gjymvN6YkRetFqbkdmmYxLO",
        "x86_64-unknown-linux": "sha384-kgHLqELA5LZOdGHVIW7kJ5ZNiSDSZ6sfHgr7sMzCRqwoGC9nZb7jdDvRqrDx4CbW",
        "aarch64-apple-darwin": "sha384-VV47yjk1RiHzrdhrn8J7cd69x8EPC/lUk1HKPNFrDfvl/pwzKqywzHgLauP4yDAd",
        "x86_64-apple-darwin": "sha384-+nnrTBj+d4JciKogRucUPnoJArmq9KiFMO+FHC6O2ZV9F4JhLPaXtN6lveqYPieL",
        "i386-pc-windows": "sha384-jKyIESEN14wAwRyXTUUxggTEHbsWW0sOn3mB5Y5EJxDiPONzfHNH2njC0Y6KP5+5",
        "x86_64-pc-windows": "sha384-Js7NUEK9r2ivmDnxmfKgab1Elwr04c1o3OuQib0cGeWoyaxztRdRJcvI2IaqXbBa"
    },
    "1.77.2": {
        "aarch32-unknown-linux": "sha384-J4vafLFAmvr7SZXXhjgf0PcGca6Da4mQNPEgtMyJ0WnY+sUwSueTq/vg1gIn9i4E",
        "aarch64-unknown-linux": "sha384-PmlDP4aoUGUy4LnGCxYqmr53gJM2HonhNLyExBaJrTKbUyYhfAf71tSQV9lUvl+E",
        "i386-unknown-linux": "sha384-vrl+bdFZglGTq5bqnlKzNEDL9TfRjgzN5c1Tn/vx+k90Q0WBsgCSpv5yl0Srqh3S",
        "x86_64-unknown-linux": "sha384-mzMRxH8+bEVpOK0IPzQVvEnSteLxPYQceJ2WPNpGE5hfWC0efge3daX/H+7vZL4I",
        "aarch64-apple-darwin": "sha384-cfzNgStKUdmUOU8/MRQQ8ZwMi9dgguoUv8Mv/vO3+3hzlqoh3bGXkNbXMFsOiv99",
        "x86_64-apple-darwin": "sha384-RM2U6eo6RUjKhDJtFmlj7YnXoA/hB4zNN5wsCHhPfRS4JxuEAoRUs3xfQix0AAFr",
        "i386-pc-windows": "sha384-V1BqExVPqQQkUD3XEZpiw71NZcQiJ2Pf2443XNOV7R+3iWtozT46Z+uc5KtVbf8d",
        "x86_64-pc-windows": "sha384-ndEPdeKGt4ODj9UgvIcrY82BxLP1aOGrBLFgq0ntbUQx/tS5x8aNqAeDuelzlZwp"
    },
    "1.77.1": {
        "aarch32-unknown-linux": "sha384-fKkGCWt82Jpjgrbw5zFSD/KI7ehspeLMGsAdXrZMHbYlta1zMhuZJXp1V85haEF/",
        "aarch64-unknown-linux": "sha384-zaP0H8P+kBCizEKcKIYk9IrAy9MjfFuIIXIVxdDR27uMUs9B50YG0sVsWl45MOpQ",
        "i386-unknown-linux": "sha384-stHqflRqj+N6j9Q5ZXxkoG/kJVOj2jpXp0t01mU7FvaNws9VcH624XScN4XnYM8X",
        "x86_64-unknown-linux": "sha384-FnYQCWHmX6b26GT64EDoek0S9eXOfIH2y2qTPTgcRl55TWdL4qvoqT9ikxKhawor",
        "aarch64-apple-darwin": "sha384-BezYs6GTKnTCG1lhFA2J9ALla2Vy4VRLB3z/4dSFyVWEBDKqY8L5dR5bnB7CUIVl",
        "x86_64-apple-darwin": "sha384-j2Jd82mDF6GIS8PMUO+m3EiE1Y2KbRwHtG0hpV+K6kq4xhIcZa1jNaX4NJhR+9oE",
        "i386-pc-windows": "sha384-ZK2npRcrZm3zfcrwHmHNPGRTrGxBXsok2paFDafyroMfHR1VDo+gcn4i89ykjkH+",
        "x86_64-pc-windows": "sha384-JQbSNnGajtCsbmePqEXW56W8Q0oyS80E3q211bBGos9O8tohWmbcKkg9J/4TibkP"
    },
    "1.77.0": {
        "aarch32-unknown-linux": "sha384-n5g3uNOffrK0nfo9wQsE8RFIqQAG94RW8J9jrB0vSG5ke8ehXO+ncm4wynGLZ6fW",
        "aarch64-unknown-linux": "sha384-tUfqFaYEB0NbLJzXWhtBLNNAKzf9WCtOQn3DnCxAuKdty1xgTJtBvqcmJJrD94jx",
        "i386-unknown-linux": "sha384-XUWUKqUoYT1wX5ezCd3VFPCbk7+c6nNcKuocR103vwjlgUHmRRD4mk9Y/Wut33Dn",
        "x86_64-unknown-linux": "sha384-02RWMhAz57xt0c4iYgOLtpzUN1e+wr4gSV1Wzp1xCy/Nwid1QDmr9x8C9X7nKo31",
        "aarch64-apple-darwin": "sha384-QfGXLQV/1bGaK1imSjQ60F1vo5kcOtabwgRzG2BStbjJ2GDcM/Vu06fx70Q7rB6t",
        "x86_64-apple-darwin": "sha384-UUeV7uYsiA2GMXpVZqre/HmujoyXgDl6gQwxSIhF5CMz5QGo26awgjKmvO8dCcH2",
        "i386-pc-windows": "sha384-xVA0UbX+a1tfwpe2r2IqsDJiqXLSD9Hbfj5mV8PSUvF1cNFUgNo9bI838Ndcymaf",
        "x86_64-pc-windows": "sha384-sQXtPCeo0Cs9k2Y9xaSbuP6/rdZpsmoaSWr70M6i4yewHKhpB2ZldvzGF6TBad90"
    },
    "1.76.0": {
        "aarch32-unknown-linux": "sha384-BYfHErxGVd5DlX+MKa9giMEJ7T8LJcvcS4lG9Aqblwp1ahk8FyB1ZeRGsgdYowdM",
        "aarch64-unknown-linux": "sha384-Fz3PDxDGoTKFok0QNYaMY+3JXgINxpFiAcO6r52mLhYHlS8kYwKpI3MF90mi0KoB",
        "i386-unknown-linux": "sha384-Wq9xRFqDma3JhMUaUvZFrUhBWT4QoFoQ5CRKp002QCsdq0MSfisvCI/GdiClZzpL",
        "x86_64-unknown-linux": "sha384-6jBe7IwPkJYAHQscOW0QVKNxDq3NAINAnRNr+8lEgHchVI7+pHC9yyP/aeVj70Wh",
        "aarch64-apple-darwin": "sha384-KyohvPbsxoPPRQ4J1XrU8z/2hIRXunoTzofuIJCXvK4Q8D6wM5qG0U1ugm69yKoj",
        "x86_64-apple-darwin": "sha384-2H3sIW/5A+BRCyQpgeIQ24gaBioG4y2Ehl2WzZ3s9+zcS/gkbvzRJzyzvzDw/5f8",
        "i386-pc-windows": "sha384-Ha9+RNBxecz6O3sf/ud2lBrWfofqanMllSl77KNQtKZc6t0WJAVr70vAJtko3yDi",
        "x86_64-pc-windows": "sha384-oRj8Np/Qx3XNVwGjXKwMlfg1lUz/7z8TkpOExeRE8897kRttfrvwxSvxiP4+Kwnv"
    },
    "1.75.0": {
        "aarch32-unknown-linux": "sha384-Ov2+inafo2yPjjrc3dLpVSn8Ib0ZUbPlWHQ7tL9oU1OlObJizWIcSYJAo7JTDtYu",
        "aarch64-unknown-linux": "sha384-inja/0GqqFeN8HimVOpc+eBUmX/eEkrxqoixIhg7Ba3FJv/cX/FaK6duIxgONp9+",
        "i386-unknown-linux": "sha384-tYfHdBoy/TmvRkYtQdfTvpstHtgqeI0x2saeAtpSEYpV/lodqEt9ChSvRNX/HJYC",
        "x86_64-unknown-linux": "sha384-DVhdvETENbSmJdz/0ClknHeyspE9nJ9sNIoWjHI+Q/y7JHvYrFdNrv1AjvRcQNex",
        "aarch64-apple-darwin": "sha384-N+pnGPdaPGqYT0SDk6l/LpgukQ7M/O8rwiRrGTv+2awnbIPasBQgW65UXH2Sk3xi",
        "x86_64-apple-darwin": "sha384-7/j8Y6UbskIIGhZ6mqNsSuSQnApL2c6dQ/F30eIjWNz2Nb3JWumV4iOyHmXfj47l",
        "i386-pc-windows": "sha384-g2CWfMB0aHWqYRzwgIsifN4bcwrdnTW9qN+siKi77ATkI8PHZhjBTE5Zw96lB3UJ",
        "x86_64-pc-windows": "sha384-LadXXQhzk7110MIocQc9Ut4tZkE07qLp+VdlnvZ5ypkgBuH77B0zjI/aed5B+tzu"
    },
    "1.74.1": {
        "aarch32-unknown-linux": "sha384-ZIlW+t5gGjhhz40CRhoktQNuW4e9WaW6GjcfbUohuLN/R2msV3ZKziG4uhGXVIOQ",
        "aarch64-unknown-linux": "sha384-36AbQvbq9OEbXgpqQuHoT2JkM/p5n0ByapG4l+qXk0s5FtcXbK1dmDd3MaX9O64/",
        "i386-unknown-linux": "sha384-fqQxNEWU8o3zgLFsQGyIR4IcprHp7Em8Dt6wbVSsAG9o9AsQFnr2ATtwS3hP1MXX",
        "x86_64-unknown-linux": "sha384-OjDtdoTc8cJFsu695NYmRff/WXzY7zEmsMeZFnMcNyA+30kCmxlgVknFKwAbRG1n",
        "aarch64-apple-darwin": "sha384-cas6nQ+K3dB437GTo2ZPaH2jWzIeTdxdYKmtPAGqVrJ6RNY061LY295zTrxbiaxX",
        "x86_64-apple-darwin": "sha384-+RHK9Ohq4bOEWV0e8/CfOPGCvJrtMtWFPpBsKXaCan/KF+ngODv/ceyJdHgAL78q",
        "i386-pc-windows": "sha384-RU2mCUqGhoPaqDt65sHu5U0ckfSsIHz1nqmVAI7ADEHq04Pd9JBWg3D0tAR2SHSJ",
        "x86_64-pc-windows": "sha384-42NaGsuc6SXdCj8oVhsi8QpesGD88z5hXNagRfjamaFMPdf1IgAGrKFskBGY5/j1"
    },
    "1.72.0": {
        "aarch32-unknown-linux": "sha384-9HieqhSzRMmQ4Z9We0wjZAG/R67NAz5Q/dRXqApWpcQ4RWATeRQcKrkeEjkjqwnG",
        "aarch64-unknown-linux": "sha384-xiecez84WBYRPZfPQNGG3Z6Fj8WBGzC1Cxp9MkbTPehZNXXGhxJycNb/uL4k9u/U",
        "i386-unknown-linux": "sha384-yGSakhmJ7tCPxGq7wh+A4FcndIHrbY/79gf3Zb/r/6bAuQs6Re7vit+RJYte61sC",
        "x86_64-unknown-linux": "sha384-bBvMyE4cK4/gcMN8stDkxivrG3WqQSzhTqOdgpjyE7JOI1HvDHIzlwcIQfBC9/zZ",
        "aarch64-apple-darwin": "sha384-LtvvYejwowQ6ohsl40Y13Y7glHThIz7FsiL3POxWYppSLQCOHGNnWlQtGR6Jh+Bc",
        "x86_64-apple-darwin": "sha384-TA1WYuoRVAp71ydNwrOqgYDsg3E1dPgBNV4f+mwAmT/PaS9i4n7gtTVpifXekPfO",
        "i386-pc-windows": "sha384-o3rd8oH7DZJvqJH5Vf06HWzcWXe7zeDgat3KpcwCvrZbGjDdXDssopViN1HLTyhy",
        "x86_64-pc-windows": "sha384-lzJT1QyxhibTyhzryHGpLKdJw3eNCU+/Gf6bLmUEtaRYGm6C/N113eB4U1m/orwf"
    },
    "1.71.1": {
        "aarch32-unknown-linux": "sha384-v+5p7dcJDy0nYtICut3OUt03gBWiassjCUfdwRse7QTcVNuP0mqAb5gQcP4z1RvJ",
        "aarch64-unknown-linux": "sha384-MPHBgxC2M5LhCx3Z9eOpoBq53LJbzBa6p0WyGKI1z4jy6GzL/JXT1pmcfBx3Zg8P",
        "i386-unknown-linux": "sha384-MQq4AC8dxhRDLIPsupeQDiJQL2+gnvXG7QfWPMmpoQVXeHM3FkdmhC8lto9sKbFL",
        "x86_64-unknown-linux": "sha384-y75qw5b47LEKqv4Q+IFTN4Vh+LKZI0io/yJcbaOtahEabXnsHSaPl7MJWLbDgCQr",
        "aarch64-apple-darwin": "sha384-5GWtk67CD9U756tIC1BB6fukBzGWMTXMUV4YUm69+4XegJELVU7siiIcPBCZr+pJ",
        "x86_64-apple-darwin": "sha384-MiJ5P6LlssqMgjLNrZtrbN1bLLseFCjuPaOwfFjOLxzxf4J3coZUngBtacGometV",
        "i386-pc-windows": "sha384-35ZRiDSH/ASTbMbwT4N1SM3HwN4S50VXBaib6QPAZJS1XwI1dcPIANc0HaktSjNT",
        "x86_64-pc-windows": "sha384-XzpvplXhOqSzp71Lu7QfRJw6oPUyh9ukuUzoBwM9GdFHBOUMKa6OktrjhbBcDdq/"
    },
    "1.71.0": {
        "aarch32-unknown-linux": "sha384-uAEG9UtpSGjMDPdGd8BwrMueanArVnggcDmodD0/uc1R1jJRhVmoB2UfHFQ9UIe6",
        "aarch64-unknown-linux": "sha384-U6NL5PCwsJMz6yJ+l2lfZb7JRu6Z4Gb3l2h9T9YoIs5uUkUKEHhJU1drooNFhHfR",
        "i386-unknown-linux": "sha384-Cy2RfHchsYZ5BzG986PWLlmydcD/5BqY/ZQr82danEtRYejDUcAlFyc8q49/DUSD",
        "x86_64-unknown-linux": "sha384-WJPsAjUpRz03KVDjg1dohYkOkvD6D6xa2qHZM8x7s1J8uRS47pPD2gujHgDG5Zxc",
        "aarch64-apple-darwin": "sha384-Hb65svZdTkM97WxfZIm3fGdIIMtvuicTo58OHgxPSydiKcMXQXbso/xDFzvK/tQu",
        "x86_64-apple-darwin": "sha384-L55eNzTkKpLyCTjLtQRI8FE+DREzOufb+LAU61V55BeFvR6qFIYd2FTziA0TUXai",
        "i386-pc-windows": "sha384-aVksfS2zBNUtLOx9ZV3sSGhd+Y0CCLXR6RZ9jo4oEdiWXc/O+i7wj3vMmnBH+Ni5",
        "x86_64-pc-windows": "sha384-5u5znV7wIEEiaC/oFUJJ9DKXhjtKpmTIPOhv0YuyPv5orHp0i0/dgzS4J4ysih8p"
    },
    "1.70.0": {
        "aarch32-unknown-linux": "sha384-uxhSlatmXOMZO15q8I8g33uFyaI9cRvSv1GO2j2xkjG7bq7U40cXgZe+GnZnsCsA",
        "aarch64-unknown-linux": "sha384-1SjtW8eGyMoYUAhpRAR3nXgOy/0BhR7x4RIxy8aWBQN+PPLhovZgB+NaMCYI4FjN",
        "i386-unknown-linux": "sha384-ddh9hJaG6cihP25QpcXH8EU6IY/CaZ9IImZV4TWcIq2M00ky5i/TNOa2Ys12Ld7m",
        "x86_64-unknown-linux": "sha384-ZtCPpIQiCCcNNp11cpocQZCIeFTDDDuhIDZ+r5zkwGLmXj4FlXcpX7/z+wtg6GZQ",
        "aarch64-apple-darwin": "sha384-s7wMLXoc/q5q4ZXHtnvYywEi2Z/OHg44AtQYtFqA+mGPhekaYDIN2nHKnovyocOm",
        "x86_64-apple-darwin": "sha384-yTU/RBJCSCre8XIzUcWlSGfwoB6IlKdmnfqlMN39QBFv+MN+IXd4IV4EXU8J6nM/",
        "i386-pc-windows": "sha384-g9yaPnKOeOolwGWWm1S6CW3UvUBFYJRRho/fyc/jHCDsszPmtopk3aZSEIl2FVJO",
        "x86_64-pc-windows": "sha384-rgvw0e2FRlWPNOZAy1se5YxvCa60XNyBbxvOC/4kkak0GKhuZULQ/9Extn0Ezp3U"
    },
    "1.69.7": {
        "aarch32-unknown-linux": "sha384-s4m7vABbcyo7tJs5vDDwoEUxpsmEo1IFgil32KH6pdqE9cpDqCdtZy1HJjLHkNKJ",
        "aarch64-unknown-linux": "sha384-9hIpa883OR9X90rsqASJ4Smu5vsQs5ixoF9LPp06Lxv9z3Qiqqyyh/Z6ZL37l4W5",
        "i386-unknown-linux": "sha384-oak1Nh8GWhzFeN5ANqnSUhldswd26iklng36ehHHyuHeM7OA3st+quIWv6mW/Dmy",
        "x86_64-unknown-linux": "sha384-xDRLI/eC3zrZPrq1VJzNCIHwEryy8xXbcp5CZmBUAAGNwoDOWDrT3zsCtcMuXVaU",
        "aarch64-apple-darwin": "sha384-HH6ZtqVDiyc7JScXq8iGON1GClqnfezuBMDsMSKQOvTGcu7zFE2gs17vJUvT6dKb",
        "x86_64-apple-darwin": "sha384-AoaJa/DUBO55OAtm3bVYmazTql/0e6GWR9Dxp3DR4yN2T41nFV3JHfuHwD1boyaQ",
        "i386-pc-windows": "sha384-6cRpWPxXJsp8Ut0Og1pw26R51EJoNeIDaU2hqYDMn1s6AHWB/SlOymzUCPfsMJUy",
        "x86_64-pc-windows": "sha384-JMGlbtevSKJ6jY2pqsRzChGJ7UtmhPINTmzBLEy1PRBC3laKwlEoA4mS6a4xx1io"
    },
    "1.69.6": {
        "aarch32-unknown-linux": "sha384-T0w1krU3PL9RBI/HALA1dyrVb85LLy+7LWqYS/KoHpu2X27XobambK3uE7N0+IV3",
        "aarch64-unknown-linux": "sha384-reXZxiy+PB2CQSSR+xtAtnjZTshez9USZvG0/MaS1kQAblYp2q4Nx7JZDaR2V3x/",
        "i386-unknown-linux": "sha384-wBcDmsMplhxTPO4YXED339DIddVapQ3fkFPHhMBiZr6JswejH4CuT3XocCpXUYtf",
        "x86_64-unknown-linux": "sha384-rZn9sYip6QeLl9ZEkhVHRT0FV1SXtYKHQ2n7IJd48EtA+7HS8PXDNQ1YyLecPoGO",
        "aarch64-apple-darwin": "sha384-IaRyH5quoCgrF3ki40igegHIHPCL1BpY0pLWzBcTX1Io+Phi5mRyGl00tUwT8FWG",
        "x86_64-apple-darwin": "sha384-lErenuWAW4Rqi8YEGet2aUONDZyk6HNaSrRKuWhUyFaTRKEp8aV/KibkP3IVuugF",
        "i386-pc-windows": "sha384-jAcvI7qr2ONrUildFz8AAfRK2t4TqWyLS+/xcZ56q7vc34cAU8mBY5qG2X6Hx10o",
        "x86_64-pc-windows": "sha384-Uz0J+LKO0j2I2TOhMGIXks/KCROHxANne2VqoUDmABx4pC2+YUYxZDjbGokA+ueK"
    },
    "1.69.5": {
        "aarch32-unknown-linux": "sha384-w5NNUsBZhi9K2l4SP+6yOlOn6ZpTQuiwndxzypoBL2ytHG2c1Ur4k9ZA6Ss4hE+8",
        "aarch64-unknown-linux": "sha384-U+f/mkkJ+sYN1tVK4Qby4JW05sXv2/8ov4DI3m90ZeDU2IN/3e5oKryI46afnaby",
        "i386-unknown-linux": "sha384-blDQL5VtNLJ/hnGc+jqNuyTtlKN6Tce3dGOjQb/EMHf2FIoou3jxM+qXveiLvPne",
        "x86_64-unknown-linux": "sha384-kn6NbV8cL/zAh4lGrFTnXKOTcM/ya30kq6i7tBt8a/rB7btY+5zqbhiEsT5fxqOp",
        "aarch64-apple-darwin": "sha384-FIdfCtedwOXtutEO5ezDy+Fx10KfAtxqK5qJMn55uEXdFDLTl/Kzy6oCvdM6wSFu",
        "x86_64-apple-darwin": "sha384-twsEZQglK7HR0WKCFDS1sqp5Q5spPHl57gCSbrsnWeyFraMCGJcz/EoQrhkvgtcJ",
        "i386-pc-windows": "sha384-Yz5DSlc7ILapSsiVH3XISPwPBIGIkV2Dmrjo3QaxbmPAB3s4GyTvYT4seUT6hqvw",
        "x86_64-pc-windows": "sha384-N6LdwII1IHFirItX5V9py9t1b7BtqcSSEg/1e5/oAyR0fgmHy69Jt1zAQh7CJmPH"
    },
    "1.69.4": {
        "aarch32-unknown-linux": "sha384-rWvmme/WV65h2IkiPwLYBCSatTag3bR0Of/XRetIyJ+eYGggIZKNJQGeVFUMUpa4",
        "aarch64-unknown-linux": "sha384-ID0fWI0uJ13bapayySuU0uYdFt1re5E5Kxr/8RkrcymzS0iUuVommEyW8KWhRHrB",
        "i386-unknown-linux": "sha384-jyuEqb3ijVkhGhxUmnZRr1j7Jv3nzCRzU2qP4lC38eJK2tn5/keC6cczbd2koNf2",
        "x86_64-unknown-linux": "sha384-8I3ejEDWgd1X7EL9mQG3/ZPag4Ld6b+TD4YDsfvMB6uLo9xDLbAlGSpJsHuDM8Su",
        "aarch64-apple-darwin": "sha384-OOIrsg0HpTJmJtuVdLp2AKIPw57aPbr41nwCEi/iyo0P45TnoClfXTqDUIdmGjml",
        "x86_64-apple-darwin": "sha384-7zpIE7OZS774vNEVdS1v14WGm3K2YhFbY2RObRIOv4KI+WT5MdxyH26yagtn8oFW",
        "i386-pc-windows": "sha384-lLmt7uqzouPF9uD7WSPl/23zFfaGBt7w2xDuQLF51A14M+JtjUpx9xkwAwRLTj+9",
        "x86_64-pc-windows": "sha384-PZ71GJgvutsiygEoxOWn3EvHLvORq+xfCmq6zyHBgapvgFmt5dSs7hgV3IZO76hp"
    },
    "1.69.3": {
        "aarch32-unknown-linux": "sha384-Ac5ywvt9XmNrzginhLc+xoygL24AjSxbftUmKpzs+z+bT9CJmsGwA9k6w/OkcyF/",
        "aarch64-unknown-linux": "sha384-Pi9XGvVCUAlBetflP5IH2kaBgGVq2wFMzdxuzC0oI2Yun8ZqfxGUNXHKl1zF+Q0R",
        "i386-unknown-linux": "sha384-y0NtjvYYQ7VE4/Ck+DMNwZNbu88CvhZHpYsrh9sgcB+SZcMWLP3ZgqclI8/S0ay0",
        "x86_64-unknown-linux": "sha384-waM3JjI+LX/A0ZqqjHFMHmUFvHjqR1dPrbz/BKeagDdZ2AK7B0vFP4c74QRGPv0E",
        "aarch64-apple-darwin": "sha384-5T5kUi0g9u73LYd1BS+A7/h40G7OqyfDioGRciswSMdCejokAvdYwsezyWLP+Iw6",
        "x86_64-apple-darwin": "sha384-NkxCyIds/glWRXyKbbgeb2ClTZvqZq+jx0pIpu4O0vrH1OeEZv5aG9uCCIelT1vV",
        "i386-pc-windows": "sha384-a5mHGAZZ8cLMeCTKzE9qgiHe5Gseb/GxeFDJ7CXkfSbDruieovmhllGHCz2xNeFK",
        "x86_64-pc-windows": "sha384-GyKXqXja5bgLg7B1zuUBxW0ClL/JMepK/YO2g9+sTCZsmBv4nRtUmHQky2J2RPO6"
    },
    "1.69.2": {
        "aarch32-unknown-linux": "sha384-+um6iDkW9vABHgb/hziyEiRJjZMsREGU0WuMkik+iRNK86JBHdK1DgMpGi58MeeW",
        "aarch64-unknown-linux": "sha384-KPOkikNkfTgCYZi7ut/XfEFR5JmWYzqstplgXIccqmkINu2FaP29WOpeWWXrTp9v",
        "i386-unknown-linux": "sha384-j6WK2KiGSspsMnIrwiJo1evLRak5CQNYdLYpDDM1fysFXboSMs9mFlkOI0SQp8YN",
        "x86_64-unknown-linux": "sha384-2blXKWw8V3c24yfO36ZA7nARAYJVCIuRtueKHBKGMOHl3cwMHNz4on9dlJNG0pmy",
        "aarch64-apple-darwin": "sha384-MLGncaiOU4UDytC75wVopei6xKvz47Q5D5UrVRNF4tcKGf/4XUUlP2rrvME18lKu",
        "x86_64-apple-darwin": "sha384-0SgxpuJ3ZaQ7EsBwVVvzf3N3ZdxRkPRpPs5EIWZpZ6iwWKPfTNaK8iBFoMa99Ss1",
        "i386-pc-windows": "sha384-th5hjce2gPmT2P48vVqaNZ1UQVUOU7gk2wqoB1sXihzCheVySzv2twuL7it1j+tW",
        "x86_64-pc-windows": "sha384-rE7i6x6v6kzachlwvtSASPCHu+skf7x0F/L9IEpN8oW92cV+aA1oB3emiHLmVqeS"
    },
    "1.69.1": {
        "aarch32-unknown-linux": "sha384-QaUa1JGwMvGoH1Nb+hxCriics/3fgoj+2t02NPJuv8N/xhSBzuyv2SuRKmGQUEij",
        "aarch64-unknown-linux": "sha384-VBLF2h3hcC1LjffhASCWzFfVuY9gQRWC6JPrF24Q43k02OSd3ntyIDF/IvAOsAQ0",
        "i386-unknown-linux": "sha384-XLcxR76fz1b1u/UIhlBNu4TBf3dorh4ssdU80S4xA4mancmfZUgq4S7sh0rwt/lu",
        "x86_64-unknown-linux": "sha384-aaXOn33YU2s+5ST9uWGnLaCwIPmWNrzccg58JDXATBEhqMBpxFSuxxzbbn44Mr8n",
        "aarch64-apple-darwin": "sha384-FKDvJ0dXDaGKbHar8+422qFdM6WdF5gSKoI1gi/13oba3s2N7tKtt4dWPwJLrlJF",
        "x86_64-apple-darwin": "sha384-UXpvRzhmxQHkIf0Z+8trpTmpj0+LHXKXTa6sY6M5ALyJzHgqGfV7f77IW5xfCUAZ",
        "i386-pc-windows": "sha384-e6O43+DPYil01CazFbo9f/mvvzcIgjL9lAWaAJ4AV9O+lso8wu/vZilovkLFYWkE",
        "x86_64-pc-windows": "sha384-CRYXrt3Zw6yynVDXrVxobAiXS86uEUVKwlTY8DNoVYzztlLDHoXol9G6utzAzeSY"
    },
    "1.69.0": {
        "aarch32-unknown-linux": "sha384-KcOxATaN6z1RC4U/jaQ9z7kaEzAtJipXBzHNIPX06J5biwIVR9dpEACsr48YzfPF",
        "aarch64-unknown-linux": "sha384-UR7OasbvwO4ONChHKGog7XwQZA6NgeQxqD71WogUnV2MY0olsNJlxK6mYQuRm2cQ",
        "i386-unknown-linux": "sha384-rnM4aSWUpKHpnhSwyV3IRKQyYr42loajqehsjrLpmcenUjvPD2NItfn+M+r2OlPE",
        "x86_64-unknown-linux": "sha384-iQdKp6YOFmW8FmyM8B+ZDGZNzPVqx3qA4N5APxGyM5YmEeX/hVI/8jFan8lppjv6"
    },
    "1.68.0": {
        "aarch32-unknown-linux": "sha384-nsmjlnxLVvKZeofawaJkMdzgxnzYfdQHHIvHAuj+q5Wjdn/35LuHDBMwnIyzm1np",
        "aarch64-unknown-linux": "sha384-6CvMgSYyafB7RgL5glb6rFoXIR2BWamCBXmBrasDxwmTIqS04Y+ZkRC+DDrIZa+6",
        "i386-unknown-linux": "sha384-qeXBrV+FoS+n3r1JCYs9KT147wHPkapRER8moe5LE0obVSqjEUyXfODOhbbo8LO2",
        "x86_64-unknown-linux": "sha384-arAUQKZphqmdeQPsVvrR3QMRbcgQjo/d6SkKbPg+54ZuJRA4ul4n5J4Javdch2BF",
        "aarch64-apple-darwin": "sha384-G2MJzk0PW8A/OUIFfgz5tQ7e+DsEWiLYaOdqZc9rNhIEKltLX0ZW8i9KjMEYDVYZ",
        "x86_64-apple-darwin": "sha384-54bAEoY4Swg7XAhsjUDmtqBgK3ZZ9pQxb8zvD02Ez5NsCJ+7rlV+aB3p/Zbo1+dV",
        "i386-pc-windows": "sha384-ohpUMqjhqqR750hFPv2pBPsNhgA/Ka8RJm59TJD4piqH6/5eioa5161RPnU8suaQ",
        "x86_64-pc-windows": "sha384-6dG33zyIoZSUh4YWux0LeHb+gQLayQvdnFWz/D5aMf4sIiZtahf2njCZZo0l0J2o"
    },
    "1.67.0": {
        "aarch32-unknown-linux": "sha384-zIRpk2EJ6nv7z6oKgKHfkhY83cI1DExyC1XGVZsQ+71c2LQ2wrZntZMT/BK6/cQa",
        "aarch64-unknown-linux": "sha384-Vuq4Tv9iTwExeeSJZMuBEJyPx6Bwh6WdY3DN7Z45OnZp38fPWMuyqlCuXpmW8jiP",
        "i386-unknown-linux": "sha384-NxW0hXoFeAulJoJfhe1pkwpT6N1R3DCow7u2XNb2+z7CfjCXHO36V1Y6zBE5IGIB",
        "x86_64-unknown-linux": "sha384-dKb0t8cGJlNjNV3l0p8RMLV52Sv5bk9TVnvFmCOHszV+0BCEk+7u7mC67yCkPaFY",
        "aarch64-apple-darwin": "sha384-Adu3I1T5pwQr4XIAQXHjJuXJrxnpwGMhQUx/fDtfC0LIBaSvyAK8H/HDD8Mchhdg",
        "x86_64-apple-darwin": "sha384-aAGvOcvJcB6WypGd+0zGOfHKlYDFK5cHagmwbZk+eHWPCzC3HwZC+dMBUTwDKelC",
        "i386-pc-windows": "sha384-tyQ1dG7jC+KDcV0LEPhGGtONnYfLRfITuFkISEYCwVGKgeTuTUxKusSQsMcDdT1F",
        "x86_64-pc-windows": "sha384-JIGS0vjjaPAOz8xzYMYmAu4hdJgGqA6UAsn/WGhOyuGhEaTGa03/3+PHuOos5O5i"
    },
    "1.66.1": {
        "aarch32-unknown-linux": "sha384-icUvlEAGxgpsB+JUiRj91Qf7siMpP7CtZXLrgFi1/VbATuuqmZsztcc+maKezEOU",
        "aarch64-unknown-linux": "sha384-Pdh3CoR9gJ6rOiNGRUE9vTx0hRm7C5TrJN964ZyFQBdf0jE4hfkzMagAjmmiIJbw",
        "i386-unknown-linux": "sha384-fQaDgUJFIqX0WvmsQjNxzXeHYtGTuxacrwDYFmo4K5HczHaUbODBUrTQQxNA25Dx",
        "x86_64-unknown-linux": "sha384-BZUfrcLWEwRbicVR6zQnRh9NqiF4rKQaMEQMNFC0d9DdF9TZgKs3ZJrNpCGvkcDe",
        "aarch64-apple-darwin": "sha384-WeXQdB32nmAGQQeE3vBF1Wq3cfDHm+CLtYj4nlyu22+Q+JPvxxP8BUwPyKb81idr",
        "x86_64-apple-darwin": "sha384-vrXfBNvhd0AKCojOGr5l2IWqheBfy/tNezBMGqHawkxgoEqatygqVvV8lW4b4+E4",
        "i386-pc-windows": "sha384-Pk/S8SfO/9ok5YurfSfbwP57hI0iuo0r4hfinzDTIGlEhoUbJT/nzx5pFXpQ0SjK",
        "x86_64-pc-windows": "sha384-YfklAPIF3Zft7IaOroI+RktH5NI93HIskuxSAvZwFzFyrfiv4UfPnyXNIl1kvP80"
    },
    "1.66.0": {
        "aarch32-unknown-linux": "sha384-4Nzf0frtgDG07tTQHEx1qsxIcDbR3cQ1Ovq2efByDRkOgQ0axMTF9uTiIkMU4cHS",
        "aarch64-unknown-linux": "sha384-111Gt5Va4Ds6mxwSbHbilefWYHfoYDlDZwC8HLRuxG5H/Qghr7IN9m9Iimg8iwN4",
        "i386-unknown-linux": "sha384-/csVwRbJHanOC0NbTut91ph08p51/yhi1Qp/rkwTzGe9XMW3Xces1FEmURA1vwcb",
        "x86_64-unknown-linux": "sha384-w27JbiiAgPhJjQ/p4E9B1VIBfdyfceBI9zxjnZWX8fDRxUz17po9NTqpc/4XgquM",
        "aarch64-apple-darwin": "sha384-AyKgoMHBj5+UrIovAL28N89W16hnh0iGB/WxPY2fiGgK/aeOsOI7Ggc43Bk3XYC7",
        "x86_64-apple-darwin": "sha384-mr4FdKyZg6UuDrDL+izUw58UqjKXRfSIQ61gkOTbC9xfN9b6bDGAwFEXO677bsbM",
        "i386-pc-windows": "sha384-912phkDlasR1+nCvKBdSA6xoHmf/NpzJ4s1I4VQa+TaISoWEUDFd14MZBKeBuCSS",
        "x86_64-pc-windows": "sha384-S2acD+q26hAaU+2qcS+IEcaF7bEissxPH3De2WqkAVtiNmZEJs8ZrGMakuU1s1zH"
    },
    "1.65.1": {
        "aarch32-unknown-linux": "sha384-W9IOFMnjvMIAlfNHTdTDQQ33nQKBCF8U8wqdgeAMkPxZ8bga5ICuRTLROJXXovLc",
        "aarch64-unknown-linux": "sha384-cE+ELD4tPzjqB8ZU6R2JWN35MvvNZWxV9gzZCqxxTw27rc/w5vEN9RjDa6rGB3E8",
        "i386-unknown-linux": "sha384-TW3iuMPJc9gVeSNDALd6kPhngpvMWvc7MUA9QBkXKszHtDkeld0k1j/2NHuf0p6P",
        "x86_64-unknown-linux": "sha384-lGViNXK132/1swoz/3dROpcid2RMmX93jwu6FH6AIl+X/gmQ6KBmFISu8w/75ZNz",
        "x86_64-apple-darwin": "sha384-ZbiZ5zh5kSBhzCvuEB80Mt+t3Inm7nCrTKUgLgxS0A27byLhd+bRn+TMKwnuShD2",
        "i386-pc-windows": "sha384-lFspYa/VAP0eIFYdN8HwhLLQZwQ803sVxYT7QW0XOMBW8w4HPXL+Z09oAxQDYvZh",
        "x86_64-pc-windows": "sha384-gSBktlOYdo7oVu7daWBMj0mX8o1DcwjdcwGcvd7LXPpVVBhZWtPmyG6itFsH7KNN"
    },
    "1.65.0": {
        "aarch32-unknown-linux": "sha384-8HGQVPSaN4sdvRowNdl+G1q+UJUmKwRdyhplzO4nKm9iMBkkwPxeAs2f38WyjM/E",
        "aarch64-unknown-linux": "sha384-P5UaHHhOxTfeXrj5Kdk5bRY+J3fw2uCFrrKn3nUV32bqBk5EncdN0qALa/wo3+dY",
        "i386-unknown-linux": "sha384-zHVdsRy248eeCslHkwThtDrMB9BN/buVhh245M1HtVKYKKyHAov4axugFnh9DqKE",
        "x86_64-unknown-linux": "sha384-h1oIF9r3KF+qySzm3s7AwYzh9mQEZ3Pp95e701hkvwUr3aQG3P+hJlqS0HytVlsy",
        "x86_64-apple-darwin": "sha384-moDkzZUaEWDVnw1QLb3pC1EMRkctZyAB27mgj3ad1ZJQbzGYL4wyKyGF8MwAoGX/",
        "i386-pc-windows": "sha384-AB3oOT8NfWM9j+M5l4TcLhIhxoFF+CMVRv4zo/SvAg6MaafWbaI/c/1udJXWuP6S",
        "x86_64-pc-windows": "sha384-cNnoUUZKJd/VHiqDK9oq5X7BcWW5EAPxtrCweoR5I3Qw9RyhjCpilXsxePMkX9vx"
    },
    "1.64.2": {
        "aarch32-unknown-linux": "sha384-gsF3uvEagFTBaGimWPDMB1yF7B3I2yD4ehOt1PZUukO8Z8gbZCVS5GN14q2qI3zi",
        "aarch64-unknown-linux": "sha384-f8VqIqfSu2hgL8fpmcURDeZKk/7qQehvBScMkd1ucahfkHITPC6NIGaWzou3bdyZ",
        "i386-unknown-linux": "sha384-X63pD05nklVsZGmaTpCx8BdVi+xwcAbPyXq0XpM2Xa/JU3wwENkUshygKDb6MWiL",
        "x86_64-unknown-linux": "sha384-ZZjijPQ3LAEyugtPw9gHd6FwHbKI2W1BKRcN4Zou26s7fz0g83PzFvjDGM6FfcWQ",
        "aarch64-apple-darwin": "sha384-FGOBeiDt7xQCQpSRIBCIUAKDqJy9jAdtpJ2A/szKAxKy7oTdZ/md24MRXec+BG86",
        "x86_64-apple-darwin": "sha384-zrXEYayBr5hkzzi90+IAjCPbq9+APyigxRH2kfm4tCR+POezkLC7naPNYDVg4aJY",
        "i386-pc-windows": "sha384-lN7aqrXDoDk+UB1EM5Llcm4POodJchxT6On2swPUnrazUozxpN3QcdNyf4YAZ3c4",
        "x86_64-pc-windows": "sha384-femKJ5LJ68qtt5Ad2SCyJM1LqT0MzarBIWqxIzm8YAucKICyYmWTvi37MW/NtN7X"
    },
    "1.64.1": {
        "aarch32-unknown-linux": "sha384-iMgCFHyRXMFB1OLW2fFiK0WdXdlUjqpREPrqYIRSRJ8IBZ5fLvFeojt3/ElGhRMJ",
        "aarch64-unknown-linux": "sha384-LhUgabtjQoD2XSwexjK6rUMaC1WRFhp6DBXtCTvN6dTibTpRVzRs7bFGMVEZWGuU",
        "i386-unknown-linux": "sha384-f6iR7Bsfa7sn1gb6u7trGMutz4BnUtx/79BW18S0sKyOS7we+HJSXiaEHEFSvGlO",
        "x86_64-unknown-linux": "sha384-H/xHfxZmRGlLOqrZpCX2DnoO2BsBk9qdhdbi4Thbaz3XqRzjPDQgkWSmZMMYtqP8",
        "aarch64-apple-darwin": "sha384-M++hfdakwUlsL7zPFA3+SN9JnipHQXfzJLxT5PlCTaTZ3ChtKhoAu9BqHN+gHCTq",
        "x86_64-apple-darwin": "sha384-XArvOleaO+WlO6WeSyJukvVblWJ1PWUDuvlOAUvL6N6KvBL0YLqMfRhxYV1RwmMD",
        "i386-pc-windows": "sha384-GcIZAhpVkVLXwf8scrrUK8zrg4dOOHCRvqnngH4ybjXXUZK2ZAWrK12rPvm2EGKc",
        "x86_64-pc-windows": "sha384-4fA9ia/9YY9e5KW4Q//LUbCFTD79yKbR2Sc4ncxNIOX1701zkCEomX2cht0NHlC2"
    },
    "1.64.0": {
        "aarch32-unknown-linux": "sha384-yu3KlGLBPDQq/mpgdChzg20U4gU1rFgELe6W57owEwVWw6Uk/twLfz3p8u69fUrp",
        "aarch64-unknown-linux": "sha384-j9AEicQhKiNJx3AQGGjckE88SbUn9UTuXsoduJB0XzjkvTZZva88EnXmd+0M7BK+",
        "i386-unknown-linux": "sha384-WzszGhnyErk4o0+G0c0m6pi3pptwe+c1zmAeha/2BaIKbiBTdB6Uf7lKyevTeIT8",
        "x86_64-unknown-linux": "sha384-z/YU6grT07oxez9M6nrpvOtKALAikvq5y3uC6vyBPbtNwcqNl226MFRt1/MTlmR7",
        "aarch64-apple-darwin": "sha384-y//LQp8seQVN0Zcw8AVKjHQimXxsVebl4IPRspDRMMnWeIDbleqa3CB9feVo/GjX",
        "x86_64-apple-darwin": "sha384-EKNYeWm5pEV3UZdp860q4V9xmz2zCDrUzADupDvpuQJzYdZVYriSSdqu9th+46ly",
        "i386-pc-windows": "sha384-mbCYe4A39KzMNhoJDZlq/GcUVrCNF1W5bPcibLNE4K4cbmQNTtEij/GtQVN02lcu",
        "x86_64-pc-windows": "sha384-EbmUag39lJztvFSrtNfENVY8Ii27BSWan1h3aBz9a4/5IjFAXJHxuZZRs+hLAZ9C"
    },
    "1.63.6": {
        "aarch32-unknown-linux": "sha384-7ypWUQaBM/7T2w1iauqBUPusQyhw0UgiK5gX53J+LlpRvFCF10BFJZ5x6lhFs7Ce",
        "aarch64-unknown-linux": "sha384-7Y5AiIMsfXZirtIMnyMOz1yLuexaHIxOR8t9idDwHs4B4XylH154/v5v0y5f4uRe",
        "i386-unknown-linux": "sha384-cERgRJuRDeFAjVAy0zNb2K/2I2h4Bx94jICy75Lq+aTD3GgLQuoktXmRPU9EbWV5",
        "x86_64-unknown-linux": "sha384-R7SC4KuPZFYInYsLGYK0ofe+7e5IhIcIGHWweay3dmYnOlrnu7jsqp+rhuhHOy5G",
        "aarch64-apple-darwin": "sha384-B+7Jo4lFr5CyN+pSdoYZ9f6l6uxahL8HDmxsbSGxpnGuv994O4Mtpi0994NArB7p",
        "x86_64-apple-darwin": "sha384-pd35W/Fj8QuixigyPIBnJ9vGSS6UaKTeU1TX5qBaibOOvOZw2ImUunoRHXXfxjk1",
        "i386-pc-windows": "sha384-5aWBA4LnzNMJBiVkT0fy10lR7cpsDMB4Ua3W1FnDTbqYdyuJqjkJEbdg1Od8nt7S",
        "x86_64-pc-windows": "sha384-WNj3fpzeFGuzIC0jjr88DcQ81aDP8Y0rFF/G9bs5QTpQW+zbfWFX6RTryPwbHVPh"
    },
    "1.63.5": {
        "aarch32-unknown-linux": "sha384-vT9e36skIepkLvpW/bHuvdzIeGUGvqNwQkIQSTqRBPt+utDbM5hFuivQGfD79jYv",
        "aarch64-unknown-linux": "sha384-2sQsaw/3SSOrWg1qtHsJ34Wv1w3DkvmVuZ7myAcMH13Pc08PYToVQTh2FKL9mbLx",
        "i386-unknown-linux": "sha384-/tm3JTlb/+cI70tBf0p2Xae1TeZV5qRYMMYgVZvZp5CAj/ZXT2/cFXFzdADTwJBm",
        "x86_64-unknown-linux": "sha384-LF0qd5PnfGw3KUthm8Gc9uWh1l6tgSua7CZ739fOYHPqEK/3objgIrcMg+9zJpdX",
        "aarch64-apple-darwin": "sha384-0SascKlh5kXISApwhDXQjlsJ+GYcGVd5i6VexaPEJ1PKOPqUD5PpaByVDNZYCZw5",
        "x86_64-apple-darwin": "sha384-41HryjEnNrJzNT81ZrLmCsW1ykL2wNbCtVGfYLzU/LbNvio1+B68SeTcTGmIvrk1",
        "i386-pc-windows": "sha384-oeQpyKGuVs1FBrOLLfJfGxFLC/E7kSPMXWyLV2K1jzcHW1SIehpnTLFyW+NN69dy",
        "x86_64-pc-windows": "sha384-VukY9uT9imVYlDfTuClffQvuLPGn8yXeoB87xyTaFzNthaxI8UV+CKpmi7ojAHUj"
    },
    "1.63.4": {
        "aarch32-unknown-linux": "sha384-BVsVYX/FmJLxLoXG0Dv0XbF0IHTpprB8hRadok0sWaIuwpboqVSXPd5mZgp2g6k7",
        "aarch64-unknown-linux": "sha384-0YM2x2YeqG0kjStklhkC6LZqggEwMxpHNWt01psGrpnBrG8WIPFVoXz+RwKQuLP2",
        "i386-unknown-linux": "sha384-XyGSZzsBxCFcMP2ANbUu3IX1owERiqZjKS1dqsrwUJj5QUP4VhQNDk86R/XWu0TY",
        "x86_64-unknown-linux": "sha384-LhSD2OmUZJ64eteXNSPO/TXCmvJ0omxzJuzKo9k/U1ZfCLtP5sz2SD7t9/BuwlRX",
        "aarch64-apple-darwin": "sha384-S+1U00RfU4X8Ft3FmwJbWa163Kuq+VccBU0zpQ1GhVdiGlr6gKAODjgpPOtCzpCo",
        "x86_64-apple-darwin": "sha384-NWaPnk0GBusuvrJgT6GFvYfg8ELc9ECsOoa7nQsSCA2ARjkZBmvQZU2X1iwj6qAR",
        "i386-pc-windows": "sha384-lj69A/EdhZQyIAMW3AGX5JifPjFDiZDolkheOlxX0UWqatBrLBug+8ZzHjzfLdbU",
        "x86_64-pc-windows": "sha384-B0xnHBzsyp1AiLsKfNF+2uRd0gtc2pUS3FgGSD7rcxw4mFDys0AZmYM7UwveJIrJ"
    },
    "1.63.3": {
        "aarch32-unknown-linux": "sha384-KKICD9S4tzroqrmR7Lu+5iccDBuTg5Q4bC9w8FrReW6scKFmFsuPFG+8SerM2vwx",
        "aarch64-unknown-linux": "sha384-7wWzOVUH8xFQ7+osa+k9Rb9xB0gjHTKkAYeOFcFFHMpKm559lBvoXJrRx1DzNJlA",
        "i386-unknown-linux": "sha384-y8ucYCXFMJQlBxoBZWNpicsNpJe6jlu4i7fy6eaiXpEzkoSHyv05WJDmxoQhA9Ak",
        "x86_64-unknown-linux": "sha384-Vbxb8t60pUKdTbjT6PkS7Vnt5MGTahTNhrVm127lfBO4iO9urnaVcpjfAvsTAi6u",
        "aarch64-apple-darwin": "sha384-YHcP960sD+XtRqzH8D4UuJneAhCa29guhe4rzL8TLEDhiVYWEpdfGXjjl4Vlowa0",
        "x86_64-apple-darwin": "sha384-ju6DHfGsTUPbcad+20SvYpVd9JMLnAp6hdt8VmcHvF12/t2zduyVcQoEffQWUymY",
        "i386-pc-windows": "sha384-KRTLCJemaIkywl8he/qgh/0XNffoBYsfZXmHg5SuP798tjSvbh+jXF87oJX6SIw0",
        "x86_64-pc-windows": "sha384-VgJUTbk8oUupKU1lM0Az8eFZjjBB+Xoy49RSspX1owfSIliGKNhpaT5qDWOvWp+7"
    },
    "1.63.2": {
        "aarch32-unknown-linux": "sha384-DKHrf8lwG0x6JKiN0vI8ujucVKIdVRz7m3hkGsjJ6J+teXkSNX19RQkN7RS3oHiN",
        "aarch64-unknown-linux": "sha384-4MH00TPSBXhCzuN5LdrMDzOlDMMvZOX0RNM2UDsqE8mEkg2wDeqXgf6Ody4+zkPG",
        "i386-unknown-linux": "sha384-fjwF2H4S9ERdikvXOudAVD/r/ILa/w9skM4IYw20yfapjQ/MXGtVy9qiQ4mQQnZx",
        "x86_64-unknown-linux": "sha384-8W3MkOlfF52W+G4RoY1IIgoT0htrUihhWiYW1VykTEyJprLQhLp2kP2mrfSqAXu1",
        "aarch64-apple-darwin": "sha384-+CNGt21pch4VpWHP9w9uBl0FmfI0Jq2H8pFWfENI0R5+hF5MhT+jP6uM+kLr2Nhp",
        "x86_64-apple-darwin": "sha384-El3nR7fq5LtmWw0XAsbXaJICb3udSWnqqyBHsv1Y5sLzYINKkat8Tn/1NpskceTp",
        "i386-pc-windows": "sha384-KhrGE7YFKsQx0BS0eNwMy0ezqUmPi/GjNPP3KWq2Qk6lhJGO9U3lPE/fcUSxQH8C",
        "x86_64-pc-windows": "sha384-6Yic9xPISlrmYH4Ik0mZsidNkhvpZyS9z7X1xI4mXJjFAUfoKLQ3X1rJ/ZZW6uwG"
    },
    "1.63.1": {
        "aarch32-unknown-linux": "sha384-Ex+7afXAy2VdWkCq2Q8Jc+DgB4K3b/PQrjfyDGbKoCEAroMjmNh/ffAivc00NzFU",
        "aarch64-unknown-linux": "sha384-LDjiaRjzHHDPl+LCWsUb4N28vUKOcbtL8DN/Zq0iZvXXIt+NKxmEf99rZ7Gxwcfk",
        "i386-unknown-linux": "sha384-B2SYOKxFdwYiNILFTYrxGerlM3sm4N91FHzZMsXT6yQvsd2wNc7BqfpJ/VWSOwmI",
        "x86_64-unknown-linux": "sha384-g5LfLUNpeibcWFEKq4hYoFPbKl9rtwdQEcDZ0IlzB1ksEpbAtCQCX/ZkWggHR/KI",
        "aarch64-apple-darwin": "sha384-gpBau6x8ZEv7hGDDo21yTxhi3BM//zgBFWE1hqpo5iCScjm4Uj1aUJ6M3w+bC0Ln",
        "x86_64-apple-darwin": "sha384-H9GygyWBSb7O1WScSPttpog2OD2+dxT7g0GV4+IZ0URH5Gz/ph7HAqXoLbO1NlhF",
        "i386-pc-windows": "sha384-F8dRtavld5ugNkzA7baSfum/9AGcx7fYKkKhHrwccyDD1IEVGbkTuh47ii1sM4qK",
        "x86_64-pc-windows": "sha384-HP0WXwJVsTLSOcpOPRpw8wY462phCdhfnpNxSHf4IMLbdPSb0zvaJtkmGSKbtMCR"
    },
    "1.63.0": {
        "aarch32-unknown-linux": "sha384-sDd/oELxZ0Y4x/kMOlCyrbHjvsWuobdtqO5kFySrAg7GvTjXeXxtjMhBrUYP9zF+",
        "aarch64-unknown-linux": "sha384-RbGHhPqG6HpIpPrdx7CrFGrt7fJCEV3TNw9voE5ooB/hhW+0NA5E8v37D2ZUgeAH",
        "i386-unknown-linux": "sha384-cmNRdTe0v3aZzqPwg7GcrupJJO79y7mUCRouSZAHBKV75Z3SnTHMw4WKDAw/gQ1f",
        "x86_64-unknown-linux": "sha384-Sww7KTJBOxqfkk14fhAA+qZlsN7FxD7jt+ZQd8sDSIMlHqbdl5yxI7qic3fm7CFB",
        "x86_64-apple-darwin": "sha384-r1s+O71ZocYndN6XUhDpmZE9GE3kgAsBp/gKYu0HW8/aWeSdMd1oykEqzTF1N+s8",
        "i386-pc-windows": "sha384-PVBmzRjMd6cRzUrNvCMduJWsKZ525h+0Q7JFy47R9Wm2TC80F/N2F9DEr8SKkfzI",
        "x86_64-pc-windows": "sha384-1qQtbTzPBrNwWG9DuCkdPJXCV9+i8ElL0qiTG5XEL9g6QYLFzAb+GAbmoJmuyIHY"
    },
    "1.62.1": {
        "aarch32-unknown-linux": "sha384-GX4ibaQfW2rHvTHo41Qw4QqasmdLZL279DyK0h74jcm6N/haRdxW73rLiRHpm1U6",
        "aarch64-unknown-linux": "sha384-RUwTxchfCNcQXf2PRh5RKJazwV5YR3gs2ZqBpqPJL/DlS/bLmja8Xwusfx/jCyb3",
        "i386-unknown-linux": "sha384-kDYMIuP0JFo36C9mdDPhMEX8sfMoYHdeSK3TaniVGEZ4fZ9PgE4did2OaboABzOa",
        "x86_64-unknown-linux": "sha384-BFH+TvAqr5OxyYUoMywvdLROUcdd/SmjI8DbZd1KOxaxdiOMJyfo2ayZtjRoatuz",
        "aarch64-apple-darwin": "sha384-vvuKJ3/IdhR4IHXOLqyEeQRzpWCn/bYuP45HV7jApYHbVouZKWPsw4I/wjgsXbie",
        "x86_64-apple-darwin": "sha384-DL3cIOSULY/dMRm2uDK8PsNTIcf1cbMrc7Y9l3Gmk2UTTLCN31bOUZkHA544g4BR",
        "i386-pc-windows": "sha384-zLjpI5sN5pMmmOO3rEU156PTvgvzGhEr9oSLWfKtLuvHnmcbEfn6BHbC5DtE2NCa",
        "x86_64-pc-windows": "sha384-zVRuADjXAiGQSzyXf2lHXfxXzZpb0PZ+Y5iHfPW+qK3OaYHr3og2LV2SFZJUouo0"
    },
    "1.62.0": {
        "aarch32-unknown-linux": "sha384-dq9qdfhlsSF2bZLwAbjBZbwGdAJ0Qo/lFFZu7Pd7tYyfuRe6Ve1T1TTBc9rRsRu1",
        "aarch64-unknown-linux": "sha384-x/lec5qwlOGgxVMEUQhhNLAvrMRBA7G8VY3beLag+XPh6WkBGsNGJMiDTRufJprZ",
        "i386-unknown-linux": "sha384-UJOwRrd0RpNvg6skm4eDQw3cUSaElgtmdBbyWj0qouV1SBjqnMSKniPTuhS113ZP",
        "x86_64-unknown-linux": "sha384-NgifCyZZudh/nP9On86xV91TTtxO1ueFUPkGens72tYCq9UOFiaZ1JrU3QWxh4jQ",
        "aarch64-apple-darwin": "sha384-E0Tg63pJofP+rzBKqZwD6MyOmww8jF3M7PJbuF9eoi9JeSV0nqWLsAo1jFqwRHF0",
        "x86_64-apple-darwin": "sha384-U2snYOVo2NBvzayeEyTJWZXhIevo7kh3JcjbjD7J48DvjxHuwLucRJzbzBviqg/S",
        "i386-pc-windows": "sha384-TeK6QMdG3D7zbcNNkjSEe7b0zy9Guvwkh2N84e+aNJQZn2ExtOicY8ujIBLOBCMV",
        "x86_64-pc-windows": "sha384-6tE1tNOFbxBm9vQwDITM+Fq6gsU11wFMpUVxYKsoDv2+7iuysMqJedEwgJzye/mN"
    },
    "1.61.0": {
        "aarch32-unknown-linux": "sha384-dWazjSetnWR35V+x5xzdHs2Jb8+MTPNRQVFEbd6H2sc8uy4Io9pR5UYwR0bLHJmq",
        "aarch64-unknown-linux": "sha384-JPcnUTb7da5+8n2qts6NVUhpHLtgIRGB5u9GxF3iKcovP8a0Uk1CADP8NGEX1gTc",
        "i386-unknown-linux": "sha384-gmMUAiXEKEzsR/aydK+bItMqescUMovbRvKwFR19Rm9dbwXZiwmeCYWoBNSHBQjE",
        "x86_64-unknown-linux": "sha384-DDP/E8mdJ1D/NFZu11QuyQJzZgUu/K7dtMgg572CnaawwqC8iGCL0dtSS1gSgX7N",
        "aarch64-apple-darwin": "sha384-zaJsDaiT31Hnz6GZnoYRztHRGq4v0RQ0OkVeRow8ifX8/QWmwjBF6CBsb8O9V79b",
        "x86_64-apple-darwin": "sha384-oxvyrnt135T6IyFRZtKSiwn55/pZljW2yF8byhcP9azurZG/HRpeSHpEi7WB1NvO",
        "i386-pc-windows": "sha384-c9tgi/TN2NEJdAxCgqOtMhpFL6RLR/uI9hXjJgU0YvmNulJYs4Hn21kh7wTKPhM4",
        "x86_64-pc-windows": "sha384-SLG2wJeT+bIEmtFARnHD7P/fJtbiLfl65dhRXWepT5aWheNSFNzmqNxwouhfsPVC"
    },
    "1.60.0": {
        "aarch32-unknown-linux": "sha384-AmMkHc3Kat9uziA/1qVJdcPUjqMojtwp+kULlmaAewfbnGZ0RspawsATLCQ6cXrt",
        "aarch64-unknown-linux": "sha384-H8R7NuQHqYi9Q7nKo4oRoSpWACvaZqdCExUYUXIDkEGTo+UGM0jYC1/H+rmE/70u",
        "i386-unknown-linux": "sha384-MOoI8Dpdi8oYAQsmdIwBNn5ECeosZ3kb+BT3w8U49eCwLWhkxeSwEro14rwnQAyr",
        "x86_64-unknown-linux": "sha384-VDk+3OdYSPzwML7tE/l/65t2pXEd12PonwXsJquxzJfpXFurUMb3yFPu+Zy9mnVY",
        "aarch64-apple-darwin": "sha384-lVweuwgwGFBJGVcT4N6RVEUJVG3PcRZ0PB97vL3jMXNetK8JKtc3c4ahb0IFF2tG",
        "x86_64-apple-darwin": "sha384-Yvd9v2CQdCSXFg/Er4S5oMp8D6/Y7zhvzTUARmJG0o0ZoOMq+Fd9e50CdHL2Q2+g",
        "i386-pc-windows": "sha384-90bpH4jW+E2vwONic3xyQTN7R5p3ihBbO0XaYtSIMycNQ473pM42QXkqmDG7+Rue",
        "x86_64-pc-windows": "sha384-QNKRO0mup3/YFlOuI/7EJfDk8bi+XwpjjdrPo8VTopNBRthiOx3C6WtK/AUcAnhH"
    },
    "1.59.3": {
        "aarch32-unknown-linux": "sha384-SN2ebqwZuW7Cm32KwHq8l6ebdlGxAyt4+Lz2/KaH6D6QWw7h10mnrV9QAc6y7apx",
        "aarch64-unknown-linux": "sha384-/wD3XXFkAmMOBp5Xqxk5P0H3rKamkFZmVxzZVPgkRccHl3CDc6HUJWYKxyqDEwGR",
        "i386-unknown-linux": "sha384-aywURfyzG/hM7wqgOWsb6GKkNhIZZDrVdezw1bqUSSBHGn4Qe8eITqbCdUeyGxYL",
        "x86_64-unknown-linux": "sha384-9jwu/uvOoYLgdQ4FVPoxtlGX4U8flNkZsxnGbbxcghuZb19BgTcragvLG/Lk8SXp",
        "aarch64-apple-darwin": "sha384-EB2ahjWj/K6m/Rbg/A2uCzKOdyWMm2Ch1Hb02rSmD5u+AclMKob5cRocirE+NQTD",
        "x86_64-apple-darwin": "sha384-I8EJGj86ZD1E0dvRmrdAim8fK/i16gg0nenWILXwu8jM5AvNOqlbZH/AesIrnixF",
        "i386-pc-windows": "sha384-Zu4fEagWTBPnVVhzz5Dm0zamhQuusfHfLIqvN0C5EWt/YEw8kqHn1ZlPhDUbV+36",
        "x86_64-pc-windows": "sha384-Krb8Q0pmlCp+nuoEqLGHYmC3UeJ9lFOmBDiFZAFsodCW+HHOVP5T9kENsXh9U50h"
    },
    "1.59.2": {
        "aarch32-unknown-linux": "sha384-xEA5KahH0sEoTKs+bFF2JnZpVuMOVjIxUM/moNgwGaIJhcwu9k2A++w/dxUuzEdn",
        "aarch64-unknown-linux": "sha384-I63RyNQuh+x5lHpDj7HOZKb3vy/LG/W6bCUEFBRzYOnkvpZliqT3TRykpi8Atzsn",
        "i386-unknown-linux": "sha384-0SCaOq0M3b68pGR0kciLifqmYNxoz89LDpyTU8c1R7utKhHuP5kdGuz0ToF3CXgb",
        "x86_64-unknown-linux": "sha384-TdhkMArCouqbowL6lhVwsjS+rQAKpnT/2XRGmo7sHStpaZ5KPU+nne3JLI2EpB9w",
        "aarch64-apple-darwin": "sha384-hcsbT1tAwqJPzAOIN9bqve8Ivos0ZFXOjJXhIGjcjUfyVAO8teq39h2P5QKaNxOX",
        "x86_64-apple-darwin": "sha384-xyt0YGUU3pKYok6EgjLoWBqeX2A8MklcAz9RaZ5+5UjOQi8Y6qDXzeCSb4D1cM3i",
        "i386-pc-windows": "sha384-VxdQD6k3GttpPSYnnGjG1x0GAchX3fdloWB3wsyl5fOvIpI6qztfh8TUC/FZtjah",
        "x86_64-pc-windows": "sha384-9HTJWEy3+kIYaUC5xZe7M8Fo4hr42m96X39buwN2eKoNoyH65hPVzQtDHEtpRTlL"
    },
    "1.59.1": {
        "aarch32-unknown-linux": "sha384-hQtHFQyTUiaO0DUy+LZt5YDP/WnKmaKRDtBFgYAPb1T5dN7U/mNbE+4nQarwAEun",
        "aarch64-unknown-linux": "sha384-lHvMb+5aw5BM2MjbL2X7uWfX+yDBz7K987w3PguGlHU6wiKLPhCbT9ngWuz7shpL",
        "i386-unknown-linux": "sha384-71RdPnCwr/d/c3TyslJ/kgj/ggVqenlADK6o2GiBs5SNT+73IwBAvsz9605NGuhc",
        "x86_64-unknown-linux": "sha384-8YEnq8PcR5FdUU/ADUL8yYeGqPIWUmLNN4rzp07R5vtANZjfvqcxZS7gCbQFqi0R",
        "aarch64-apple-darwin": "sha384-WACvs3JlpbH1hnxAVh67/ewrD9YpXlh/6p8mCySFEpo1dCQJv8SFOKWWDTEgTNkr",
        "x86_64-apple-darwin": "sha384-TotMmGnXTMydoOzfDHC9VXbYEMrOugXtNZJ2SxAHBIKzjzotMoUqspUWhAq/JdGX",
        "i386-pc-windows": "sha384-DPzkxivvb+CnaQCQ/EJKU7/r+G5T5IlFJfEBSWsP6FBnkxT1T6wCMZUlXxZaEYab",
        "x86_64-pc-windows": "sha384-Gnv28tNGRmBQQDo+zkycq5trN4NoBZ3cxbW+SjYYyXftybXEqCHRwbMWbh2HHEJz"
    },
    "1.59.0": {
        "aarch32-unknown-linux": "sha384-svKPdy0lwPBKD0m0Knq539J6QS64UWPWgMiTMB98vOfddBHDWJG4HmgS+M/I57cK",
        "aarch64-unknown-linux": "sha384-7Y2Fh31PUHqFTXKkyO9N/jA+6jHJ7g03Fnr64KufKyGp75Mwajr3F9Kf+QLRDyf7",
        "i386-unknown-linux": "sha384-pZmcy0UVQWIjOFOfE0qUjkoyGCvflQIQjcQI0tPj7pYwSqdM/zBpE/3S1qy2QPy+",
        "x86_64-unknown-linux": "sha384-EW8Xa+XKSLR4ta+yOCD3RLPHjXOwCqluTWXTpr3Pdb9Y4WbeGi7h/OUtIYNmAdHV"
    },
    "1.58.3": {
        "aarch32-unknown-linux": "sha384-CQbhRLfDd3uvvgmZwvt2TFNRrw8nuEU31zisP4hcHAqTJ7osQIKW+lybtuo9nVya",
        "aarch64-unknown-linux": "sha384-pdRueq/cQoISvphBKU+k5pvBdxF2JVK/+o1IONYyqVxSPP7c5/bjaJWtLcBsNMsm",
        "i386-unknown-linux": "sha384-F976n3M0Bjwu7cfY155wBqAqbE/ZEjWVkpyoxEJRZBw/dDesT/zzW6VPNRm6xciu",
        "x86_64-unknown-linux": "sha384-iUWVCN5tzvUXnfU9oLedPjsB8L+hpyq95nSrbYvB+YERUVjSbTSAQZEd848h1aWO",
        "aarch64-apple-darwin": "sha384-mmW+JQSGZuGkHZLJmTK7x8US898q0nGcRTLFaT85JtV8u2C9pJ7YmihOxIs0IZ5G",
        "x86_64-apple-darwin": "sha384-GuCUE1FFr2AgAWz9+SebiFLfxYq5BVfpNKUaVFTXEEHInLzOsUd5rspDHFzmH0n9",
        "i386-pc-windows": "sha384-rKjZFDJacLlxK5hK7GzYtMPwNnywBXFdKt6rdZ5jpK0PLWTQhC3TKJEL4T4Prlvp",
        "x86_64-pc-windows": "sha384-Na9zpWqbFhPTo/VwFsZeE3J6iYS6CeHVEhxzZDSNcyNXskSbPCag3mzXaXcS5whn"
    },
    "1.58.2": {
        "aarch32-unknown-linux": "sha384-lCFQD6nBx3FBVshNQ9noLMPfF6Xm0YJKr/y9R4mwBYZB1rRJFE3vcoxCAdN+Ml40",
        "aarch64-unknown-linux": "sha384-4I9MBajSa/3HlLUYrxftQspkUQRzo+8SlXh97vAZS3MiRKf0wHVhb3EvFfHsQ2TP",
        "i386-unknown-linux": "sha384-TWI9ZSnSbMcHV9hN8+CIWo5Wgr9NV2TAvNkVRmdJUL2vRGDp3wSR0LPzSmrXGZ2r",
        "x86_64-unknown-linux": "sha384-740clsSXE7iJiVD/W9Py/PbvhyEk1IZ0IiF3JGWF2vKzichcnViYQvJqJkNG0m3j",
        "aarch64-apple-darwin": "sha384-AF2MMYuEZo/lfFzgD5PqWFXmYfWG7tUqROG0Mntb9hE61C+R0+bhJZARPUz3FL1i",
        "x86_64-apple-darwin": "sha384-j4A8Fh67E+c6uphnN3YK44AQ2z80oBebuQmdw284lqMaWvG2Qr34KKHk1tRYplSp",
        "i386-pc-windows": "sha384-I9MBSgSTJhWH3k4OsKsbjnoogec419ZIQWojp1BsGTuXpdJX93iabnHXcYUhfvzW",
        "x86_64-pc-windows": "sha384-xgCJrtVQCmalxvSWrsXKfP8ECfa8y3uPZMJYPUfZ8QX4doc1vFEYFC4oE0GvzANr"
    },
    "1.58.1": {
        "aarch32-unknown-linux": "sha384-Kb5EXAQwPpgNQUdmsueFiXaDC2mmpW+S5vqAKT7zL/KZOCtMMw9Ji86lCyZbcka6",
        "aarch64-unknown-linux": "sha384-JCEjc2PCP5LQnUJSp/YcfYJIAaq2qbcVezGP+j8iywjjj5JMi+EZ6JWkbOrmw0hF",
        "i386-unknown-linux": "sha384-ZfgX+BophrXKRja1mCwId5wUZK9+NygA6Atawev3ia8P4XLC0lKODcq8iKu9b94Z",
        "x86_64-unknown-linux": "sha384-8gaJ9qmX5S9JLhEhwj4oPoVWdv2vkzNjqofaAzAFaghFvymoN3Uka9dxMOiwkTvA",
        "aarch64-apple-darwin": "sha384-80VEfWedx326qHYq3zxv3Vf7zhNFiX17CoE49DYvM7KHSD3DDAQophrzfEgU5l4U",
        "x86_64-apple-darwin": "sha384-IGSrudWlFVV2rlzH6b6TWa/jsE8isH4nKLTiWXV/r2fZyY86iV3kWQbyl6dJCDwF",
        "i386-pc-windows": "sha384-JV9hE1vPhGcOUFWIQQGVDLV7gfFUmVjN8zfxxQquo8r9OzHnivGCo8xCiEQTsDTy",
        "x86_64-pc-windows": "sha384-iDd7m9V0NkgoVaGU19/U445MdJA67+u/14bfNHVyxw6eEMq2qnk9zKloal2UDf/H"
    },
    "1.58.0": {
        "aarch32-unknown-linux": "sha384-qeux9hCR7UCH251ZDc+0gDm94ONgJixFLSn7IwNT/U4X3gfhGvUQCQp7Ovx8ZGTY",
        "aarch64-unknown-linux": "sha384-Edrh3P8oGk7iZLYo6rWxlpcMOnMyTd38NrqZSEYKnfvKFKnyPXkTyVh1w4cG4t/i",
        "i386-unknown-linux": "sha384-nbK1cLroBtnmw35lFKoCfQdpyuucVYZ5xJEqfm8plh/w4DlK25i4W8EGnWprGtUH",
        "x86_64-unknown-linux": "sha384-PLFuPwKkTSqn5mg7yjK4szG7sQlWFQh2GsX6mDaU4pbAyZ0YIQHN/dec1VfKFQ8l",
        "aarch64-apple-darwin": "sha384-nHJaq9800sSbZDfmrcq4GvwSOj1w6QNG1CwVluMOWrvdmbaZ1Thz+PsZPHQaWWK1",
        "x86_64-apple-darwin": "sha384-Yy9engbl1Q9Pac2CfVFIOpYVas20IZV2y4HdFXkKBjDxv8gcjegx2adY+CiRgOdu",
        "i386-pc-windows": "sha384-F19ubufuEDzfjXtUhzUbmLj5nFMDP6w7Y6A+KaX4qm8qvJaia18Bng3Zr3gk4yvx",
        "x86_64-pc-windows": "sha384-Aurey3XP2p5MGi7Blhv9u1C34M5wJMpT1FdKY9TtKWCdrROGpgEnMT3tzKsz0JtS"
    },
    "1.57.1": {
        "aarch32-unknown-linux": "sha384-DjJwN8CsR8kK5Vx1tIDTVVrByhOSMIr4wTNKi8sBwWBsAuzLhzV4Lrj4nC+IekNE",
        "aarch64-unknown-linux": "sha384-skgZ8zCBCtl7RlEb/CYTUIVqlW4glYgXPWn4MF+0swo9FZe75RoPW3TTom/TWSwE",
        "i386-unknown-linux": "sha384-q4+f2652RY+nxH/qjeZBK1mXUsNZiM7KX5IvFq2j5PdshfEjPZ8TcK+gqXJOBdAK",
        "x86_64-unknown-linux": "sha384-wic5b/pWmpQxkEzzd/8AhNjKlWDMQUGWbzjmgRoq4lkCx6H03Xr9SuYBZBe0+7qJ",
        "aarch64-apple-darwin": "sha384-ZFGeGDkCYjZ5PFm49pECGTlc+1wXE7LoiriQt8C+aqVbWrC5BxUFDgy2x8njl9Tf",
        "x86_64-apple-darwin": "sha384-qt5Z/D4MRPgJryHCzuNkP6ZN+yzMKI62Kh2Ige7j03E0/KXb1MeLrqRX+XsNJFP5",
        "i386-pc-windows": "sha384-yJnLP3Nzyf4zzwslt+OT8viIl9EtjTbbKHt5pn/15lypxK8IXV2e3q0FN6Lgodo2",
        "x86_64-pc-windows": "sha384-NL/rsBmzgahhszDNtbzDRk7ZqYwS2Hj4xRf6IfnI2oZemBYNC0Vnwt73tFfAuNsn"
    },
    "1.57.0": {
        "aarch32-unknown-linux": "sha384-Th9ONGeJWPDfJAbsl0fQMfgouny3fRjwdfqL3Q8kEcgbthdyt9RL8SxDd0R1rq3y",
        "aarch64-unknown-linux": "sha384-V1yu8jpzzoYmfV5Mkb25GkMOv8eqR20EQt1mofRPc2zRwrq6L/I94MdlCjtnEMXc",
        "i386-unknown-linux": "sha384-oW6OvOrFjU0m5Eyyg8lwUbvy4cuF5uqPo6jx1cuLhioDPBjtkbE7Ce+TuidmBoL6",
        "x86_64-unknown-linux": "sha384-ZWtRCCYFWNDcteS8b6qJdNVdBaAIOAOt9dzgCrhsLGfUmCeM0yKZWk5YxfjMf1g2",
        "aarch64-apple-darwin": "sha384-yXEaoNxxqartvGp5owsjW/R4byOPIAEz+7Sjmh+j7ubCrDvVTR+9dhR+pebjgRDV",
        "x86_64-apple-darwin": "sha384-PXgT4YyPxbIj3NhMAJaIhSoQ0N8ajuFPj7sEtkAU9ObVhaZXIwgdgI6ZbBfKtxMq",
        "i386-pc-windows": "sha384-QQ+4F1Uwr+57wF2So0h8qAs41/DnnH7aPpip7dTCYDUHPQXuZq7tgVXI6TM48qiR",
        "x86_64-pc-windows": "sha384-y/dgEYNgRztShvnccIQyVqenRJYgE53pm9DciQsXLg1Ffo0453LYgLaOjgpXs8uz"
    },
    "1.56.2": {
        "aarch32-unknown-linux": "sha384-I8alU6ZtPjMB2VnSdxLJMcgyhJRmvssYWqNg/lpeogUr65SaIr6Cd2uweyNvFVzS",
        "aarch64-unknown-linux": "sha384-j6alYrVKr22GMyVRjZjQ8rj2h41zAniM/VwzwX9o3uMjjl0QC4OY6YtpbXawHZDY",
        "i386-unknown-linux": "sha384-u0yZE18cuXtN3K9DyxmZ3OigcSQGc0AjQTEYDJ0z9OhH/s6pIDrJzfu8vO+57VoG",
        "x86_64-unknown-linux": "sha384-4iPeTT6E+ARFbNhdTKKDzqT6nKZH02Fc4qAy2TA77lrBYVMmcd35EcF3yIEDqL6a",
        "aarch64-apple-darwin": "sha384-5X3MlwdV2JgAGm3eJAXnyYm6pJB2jnfbwZqso1YVlDvGOxHWLIsIKmvSY4dWhNY5",
        "x86_64-apple-darwin": "sha384-QoDW4HqdJRiPoKG7kGNVhcRirlCArMtCQ58Q93BEwuFyfwHoQYjBAhlWoA1TUkAV",
        "i386-pc-windows": "sha384-kxUyYPVQ++29GhQluPVvHSnWly9XTi9SE/iCQghiycrt1hDtQzmBne1L9t7N8xBT",
        "x86_64-pc-windows": "sha384-uHnwAPyDDTxwByzqRjnUN08OBS1c51IJzYhY/ob0e3uoVx6W2Dz5NjnKgTWpyN1N"
    },
    "1.56.1": {
        "aarch32-unknown-linux": "sha384-KhMJBr/5sEi1+VkRTpiBnwHvGRXPbDiOdJ+7Kz5oheEVwFkO/1gq/EsfV+1SsZDw",
        "aarch64-unknown-linux": "sha384-BczPbaZixyVfBugsvFInKYZ2tVChYRjvTUn+G9ONdjwV/GGyKrjtzvUcd4CrBjsA",
        "i386-unknown-linux": "sha384-9C7g0P5uz1rT1UdrsyGo3AeKipJ2PC8soGfYnqV0W/M+7u6xHuzvd8xwmvMohUpV",
        "x86_64-unknown-linux": "sha384-k8Mt9EtUuVMba7uJguj77AC+rM1VkIl5XXtM7lvl9awz5uPBp6v+R0IR6nGGqwen",
        "aarch64-apple-darwin": "sha384-yKd9UNSlMTm49QxkjENYzLBbSzFZvWE9C9j1Cqkd9O0/jRfhQmYMcezk9slZjW4s",
        "x86_64-apple-darwin": "sha384-DciX5uc4UZdMBgVnOoNA11TSqfp/yFVdFTjQ9OBFVp/sY8YXKR8Kq6kKFTEFI7Cy",
        "i386-pc-windows": "sha384-Xs821RtxCHAzJji0YDAN0aunww1hVMnOIyr/zQ9NeftC6mydA2ZiQuiqNId/4pDE",
        "x86_64-pc-windows": "sha384-lHkp9ERoqdlcMxE5v8iFTbpDqeFLtGnTsGoeqBSH96ujPdbCrh1q0iylze0fRazX"
    },
    "1.56.0": {
        "aarch32-unknown-linux": "sha384-Q1lS0/5XLBwoxJD6ORaecTpAkfN9DVqclOEGwMsBssp82LIovYFboJDh18FxQ21U",
        "aarch64-unknown-linux": "sha384-h+K89UvUlMWDXfs70ZguUTM88wBxez646WA+9rdzXH1Zaj5XsBSU4oE++PvOOkGo",
        "i386-unknown-linux": "sha384-nht7TkmxM46+7B219nWWujc9OEZgu5ip6EiTOTDfOi7fCbi81WQvY5rKoqKS8Vf1",
        "x86_64-unknown-linux": "sha384-lFq2qkuVmSA0SVbEThu5B496FfSL924Tv468ILLnd1gR7X8oeJxnZN3OOaa0HScE",
        "x86_64-apple-darwin": "sha384-xe7dkmJsphxZ3KFs/hMntCk6DiFw3TklRs2IKiMNXxSuQUgVn6TTEhV2WDGSQ3sE",
        "i386-pc-windows": "sha384-o2UT+wHeP5x9ZGPV78nnDRsLe0R9WVyttXen35cJsxYklSjWUzfTC7uMmN2TXD94",
        "x86_64-pc-windows": "sha384-qq++DBoX3UD6HJN/+cvaLkcMgzEpjc3YkNXHNh8QqFebO9v2fJlyqpomKVRyvIGA"
    },
    "1.55.0": {
        "aarch32-unknown-linux": "sha384-W+BTeNN6fn+gxXVNl51Dnh2GDW1IYzC0wQL8jGOmPDOifCqJVWUv8z0XJnvkC6Ci",
        "aarch64-unknown-linux": "sha384-ocX5gKGTFSyUhBcRJ80BTAFzK14lSoVLqp+wNQf+bsKBeWIl0xhy7uBjIj9RU7Im",
        "i386-unknown-linux": "sha384-Fm4a8v0wO6PXNzL5v+ZjJ7Ay0khfxgZJprAIOTFTkfS/QIbXWz7eYZdYLqJ2kiNz",
        "x86_64-unknown-linux": "sha384-9EXxBCyDks5N/L2fOVIlC8YUBa8tZqUbVuZeedTJsxplWfekvc6AKnYmD/z6PkzL",
        "aarch64-apple-darwin": "sha384-M6OTC6ZEDsBf1uLrW70MqcVN6XTNtnx9KpsPW+kJBqHDf3FBweC4iQWUFrPDmg43",
        "x86_64-apple-darwin": "sha384-hGUxqPO+pu6c7+v7xghDdrOBt0i9sVUngjG90gcnmlNWgPxgcWDThmKpQfhq4mGB",
        "i386-pc-windows": "sha384-Lz/rCgaNkXG4Hgl12GXlxTW56bGlDU7QzAiLNNBcGNevt/dcH/T9WBSJ4mgb5gC9",
        "x86_64-pc-windows": "sha384-4URm4Zt10Xcz7Dnt6V4YzBeY3AqdVqXRFoc9WWC4fF/66x+Na73BtgFZPwq2E+7U"
    },
    "1.54.9": {
        "aarch32-unknown-linux": "sha384-0Y7RMWC2hxxfnUNyHRhNQ1EOUh5499HTCt7HNIebjUmAcFcUSkirGInC/rpwksQY",
        "aarch64-unknown-linux": "sha384-Ys7KnX6XaLd65By+LZeJVnRCPNjZR8gkpxDu8PV5rYp/wSTLustCoL44HhQbT4Ul",
        "i386-unknown-linux": "sha384-2FrMpQOYL69QRF6pXkinGjT/AwVucg1Y279Suqt/q/bQls3vlpaGo2oXrnia0buR",
        "x86_64-unknown-linux": "sha384-VzU4i17cMSOdI2NcfjA5Y/Q14yqozNEpwKldeYhXItiv2RfSLSXSHvDUs4mJIWJg",
        "aarch64-apple-darwin": "sha384-RyBSxvBcmUSjz37RUGDxImlwQqVMiuVVYTqn28Bl+clO2kSkFkFXYh7yZvXvu89d",
        "x86_64-apple-darwin": "sha384-rW5zIfvNvYy+WNFb//U5G3g0mTKJuHgm0bjGoJFx3BQdnmSWJQ3H6uerrYX20JEc",
        "i386-pc-windows": "sha384-kKVYJ4JFs3Sb0vZP4imAKXdjpQZGFJybtKpHtRg0/YHVGpY1X14zdlrIf6ea4nL3",
        "x86_64-pc-windows": "sha384-CtwVdpuO0jhy/4jbqeD6gpYFb0l/n0cpTXy5LvRCzm4iLBmjSXTBM95dylDOzRTx"
    },
    "1.54.8": {
        "aarch32-unknown-linux": "sha384-Cf1725BisFndZ2VLvnhgOQL+AKTK4hscPkDy/ZYYpdRiajUeKYenHhE/rhMfNp/G",
        "aarch64-unknown-linux": "sha384-tgd2t8zcIMjNFDkCdeTd/GKFZEzCmlR/NSo+ZhIwo9RK2qeFk1i5LQlsAwlIbA0o",
        "i386-unknown-linux": "sha384-/b7EV47umsOGlkMUY4vFk5H/Z15/OmhCPgD/EDbdQjeftFmQUzBbHtrfPgnQIaYP",
        "x86_64-unknown-linux": "sha384-55c06voURJa36ehaEQ7gFi54Wmck+oAJ4wtlxBSBSX/12h/n3i3FR8t5JpltUaEB",
        "aarch64-apple-darwin": "sha384-8lUAWn+0fO+Sb0zWaTIKQtuxN83eTTYHxMLlVWWUzG9QMpAubkvOfVHt5o0efnq3",
        "x86_64-apple-darwin": "sha384-8YjdhH2K4d53LRN/y4TjrC3ppfeMZQjTNVItZvotFZK1ixI0MfSOcY4NQO1nH7iK",
        "i386-pc-windows": "sha384-a+Yc3lywr8xk98FV1TFF99Y6uObz2DGtAS2whd4RNU+gS67i++c634RmbGw6dqOi",
        "x86_64-pc-windows": "sha384-Dr8XgEaw64GFkTtJ1U5qZ8KiDULnnAvXBuqTJ9INCPXvjWH5LwPkPhpCoy8l7VXr"
    },
    "1.54.7": {
        "aarch32-unknown-linux": "sha384-pQVb+4yYxCO91a5TnP3XxX4rTG+MVkIqn489oEj8/48ALenNcnF691M+/W2Ga00r",
        "aarch64-unknown-linux": "sha384-qwODPBFF7xzZvtKREXOU2YrIBRuJ1vFULui9UFr6CRThbta1woCt4Xh5cu69J8O7",
        "i386-unknown-linux": "sha384-4Hka3NdPXHK+o5H/+aSgsggW30e1c4LHUvJtBz06dc5aZwt4vzEC0LPxAiZNhmPz",
        "x86_64-unknown-linux": "sha384-GdcxkQGzwRc7Bw+QDlh141OClLBhUUR0XALuARVD3SSjwHA0Bc90v4r/nWMqweWp",
        "aarch64-apple-darwin": "sha384-0Z6ejcyFtokMg+Lrb+8tnC4pqXgaELifcUk6eG/DdYEsKWo0NovKWfM3r5jzwbh4",
        "x86_64-apple-darwin": "sha384-Sahny3UZgX1xhf8RXMUQZl94D8z2u3sD6LL0hFurR0qS4fs4SUSos40V8NRODObv",
        "i386-pc-windows": "sha384-tViarWXOdEdwqlsz/qXTETyb/IcrJkfi99nmQeq4VsDnw943SHnF4yC+HsUIfm78",
        "x86_64-pc-windows": "sha384-u6cqon1AfUACi6UW2RtfiiDje7dq7TnveTVnA5N3EqgpBo1YSgJB1aVZ5HUBlGqC"
    },
    "1.54.6": {
        "aarch64-unknown-linux": "sha384-KVPO2FmbXtpBr5cMKPT9W8hq82EgH4bh/97NboBevuu8nYWW/zwGCgp8ybgV0CJL",
        "i386-unknown-linux": "sha384-SbM8DYTgb0ZBfodlWC/ybMfsC7laTPI4nEDZ6f7NoFGQzhyq4glwSSToFCZkaujf",
        "x86_64-unknown-linux": "sha384-sCjMySChqD8Qitb5I/NJdhb8D4utTQnrWHRLGG2tfKe+N9wBH9Oa2ahCYKfcSDXu",
        "aarch64-apple-darwin": "sha384-MD/WF5xcTime6Gd8SYs/CZad1jnwWYaASGcgXDXFo5sx3jxBbXfPk3RtH14jck1q",
        "x86_64-apple-darwin": "sha384-fXvxyPKIjq0566DhcbVgfzOsa13qSZitkqWTpBhf24v33CTXq8Mw5vQ3LrFMGLyp",
        "i386-pc-windows": "sha384-2hSX9sQkPQU86jdqjVorUY1Xtzc7cmeOaciQiuTrSIiRrP54AS8hTH8albaX6hkp",
        "x86_64-pc-windows": "sha384-/PB3Xc3q7Eett3IUvmO8NnqtKfZUVQXZXuxv9NouhTraaILN8RSSuuA8DzUXCzSi"
    },
    "1.54.5": {
        "aarch64-unknown-linux": "sha384-zP5WXxpmHkcIStYOzQaA+5Rk6zQaY+ShCDQvHkPiTElLuGeiq1TC7vsOR1y+swEj",
        "i386-unknown-linux": "sha384-9+BsRzmWuHjn1unkV2tQj2B5TsfCYYA0FWK1RTTMH7q4OCvH8/NGg5a2rHwQ5tsk",
        "x86_64-unknown-linux": "sha384-Om2CE98D/dNdWjt8pwNL6Z4F2yr/qYKJQ1SYR/xSJ4ml/kfv/i5472O1XaBblXR6",
        "aarch64-apple-darwin": "sha384-jNFBvwqso1FBuCPCzmgC7w4IVxeXafzbZLPS79S0WWdJt5HlfvM4pTt+mjNos327",
        "x86_64-apple-darwin": "sha384-x17d2ZKTJIdvM3wId15MPVBIIZyAcrMuZLIgMbo1ub8TELi+V7uIImOpuZ+aCLDy",
        "i386-pc-windows": "sha384-WZORz6O7EE19ZI4FT9Otmhkz3bLsDnpfC4bdmfa9wRRkK6opXo6csUsVZORnqL2j",
        "x86_64-pc-windows": "sha384-hecEeG/my3rI+DVksm47v3r6W83lBG+U9uOrNSBCqKWzOM1XM9wVegtYjfFPeq/d"
    },
    "1.54.4": {
        "aarch64-unknown-linux": "sha384-LKz1+7f83gBSH8saDm71VaKbcrGFNce6H43uxqKfFinzJLU6Y6mKu2lbqqIyvCKd",
        "i386-unknown-linux": "sha384-zygm1eDSZKX+JCb61dtoh4kRz6DWc3WEZ2vkHvdKZ79xwRpBss0mnmwdrOjSRrhp",
        "x86_64-unknown-linux": "sha384-O1Ba5UW+IQuNq6d/sI4c+b8e8JpShpPR32arfTB49tTh9LE3WDc5mzm3fsUBIde4",
        "aarch64-apple-darwin": "sha384-lr5TNOsyWn15Am6Rl70JbK8RjgzYVdoNAN9/vAnAxnaZkcAxIWAbVbwtufv4Zqcb",
        "x86_64-apple-darwin": "sha384-GqOkB6QGE0ccgGs6zQ9JZ76qS5yHvdIJER1uxV6f1sLx9OaT4qsTxF9skeF6KQpK",
        "i386-pc-windows": "sha384-gQdkJ2c7iee1ttZrdBp3KyCyraJBpN7pNxKQPr/vyaHISfWFmCW3Ibb+yQXR3piJ",
        "x86_64-pc-windows": "sha384-5gp+5g7dV9LsC/0qoRY//sy1kO7escmLwtoMej9/G2E9VogJ0TJgU27MWRKfli9J"
    },
    "1.54.3": {
        "aarch64-unknown-linux": "sha384-1LxW3MtaIccBzk28L+2Vz0i1GDoAFa1YVNaaGnK+GgvtnJlrJaMm476T5hzTVo5Y",
        "i386-unknown-linux": "sha384-jkjLJG1DPSN2dQn1SNNKhhL935FqKCYtUIyXEGsaWUwIxDmxzNqaSm/uTDjTkMx4",
        "x86_64-unknown-linux": "sha384-+z1FxxWd3vVSZzJzpPDZD6VZUhXofvzRgCRvbQfveY00EAdPNcc/psGYXRGTwOjX",
        "aarch64-apple-darwin": "sha384-toyQE39J2E20bBhrDvZ5U8gDAhuvOmJ6AcBDCWkup85yCkX3nvNFvhGHp7uCt/0O",
        "x86_64-apple-darwin": "sha384-Xrhw4/m3zHBRY+HnbM19KdUTJu7YgVABiYh7xmUvepHgkt5LrhWIoVQSct3x6OSm",
        "i386-pc-windows": "sha384-G3LYic6+pp2wsbF2Sb+dd3TUbGFcCq0T/4+I3oiXxvW8EiD7Ifshq+feOqQu0u5w",
        "x86_64-pc-windows": "sha384-2KeH6aY03K0PUs/hUPVJ3NpNcN0RUr0LAGLzzTnwX0JgB4rdmiaJUJOT95ocGVMJ"
    },
    "1.54.2": {
        "aarch64-unknown-linux": "sha384-o5XtbgdDp8Heo3tAEZ/yBmfdeBlPHQHEqZxFA7BX5Hx36Y9vVZ/VcR9gUk4iBcg0",
        "i386-unknown-linux": "sha384-MHU3DtQAqH27nkqbS1S0Jb34or364weL/H6B56D5sfS3keIXhCxxyNbVgCh/yFoY",
        "x86_64-unknown-linux": "sha384-WFSPsfw9nn5oCd4m/ccEwq+YrMzF3eF4zeuaDG/lEd23+sxWXxiDMc4p+lJrSmA/",
        "aarch64-apple-darwin": "sha384-q6rkscJ2Pp3Pp6GYg322Lz86o/MZQToPEocwW6/cBM69H9NjlL25AwYyURLoBzzk",
        "x86_64-apple-darwin": "sha384-yzOs2h9IpqHGHzMGAyKwQaLYF/ERcLD3em4wlumBjoe8IDtDGAAZdDWWIVabTKV/",
        "i386-pc-windows": "sha384-TxACUNeisOi48iEh+jcHYlwD2nXYOVKv+/RD5AMUA9uvw3MsFZXm9qgMkvt6rLGI",
        "x86_64-pc-windows": "sha384-BwG9xGL99RtJZG2J0ViS0kLm2M/Jx28Xkz5Vs4kFz6SL1urPvrBnmxt+0Dn7x8H1"
    },
    "1.54.1": {
        "aarch64-unknown-linux": "sha384-PIFKG2yvoafqoHBbrGEXQ62SjMxc8Q1FVK9RDeNBrj6arWUL/ZybUUSsSPWrFo+d",
        "i386-unknown-linux": "sha384-DuDFBbonD0yzE7x94xwR/UY/UekqJLu4ErK5ZOoPANrdR5EgTgj2ysc+OzPgatMH",
        "x86_64-unknown-linux": "sha384-XE5AjLfwaRuwhywk6yuFQ1NszgnRye5HaZMOkAjiLd4o9pq8/2o3sdARwjIlNMty",
        "aarch64-apple-darwin": "sha384-56+IurVQb2TjO/xJ7qT2ugbqZGIVyZbLqnruKiQz7qZXWn3SzWCFI40cLFJWXDYc",
        "x86_64-apple-darwin": "sha384-yuHUS7IYLuVi2bA5uYkxUJShUZaZWi++6DOKs+O2z2VymnEJhbo3yTEZCBthvSX8",
        "i386-pc-windows": "sha384-7oF6LnECuFepAquSiVkAxlvn1N4hl78zyO3iZwbon8Ya3rGVi9/ya9MUZ+N/k5T5",
        "x86_64-pc-windows": "sha384-krK2GUdfv/KpSa9ugNMZioBr5dD+khaSS1sNaoCBVQpeHz1rX+SbcFBYKI1fgPbf"
    },
    "1.54.0": {
        "aarch64-unknown-linux": "sha384-9yupzeDopuLphlR3JGPdiUY965jKexNnfe3mP7p7qGW+cfxD3FPUIpbp+ry4obuZ",
        "i386-unknown-linux": "sha384-lgnl/+ZP4qgwCbN1alnYUEDGq56TVsSc8vmHiVqEoM4ZsBPX+A6D+O6kCkoyF1Bl",
        "x86_64-unknown-linux": "sha384-kVKh7pl1uiXuc/Co5in2ubqEHmQOxiMWtnO3aVQ07/elbHdDWMV4JlQqw4NuY0jq",
        "aarch64-apple-darwin": "sha384-xKkoPvTTKdzsrR5f5wo3JUEYO9c1hBF5426BmWzTadq78WeKPZXvXTAwLvZffrX8",
        "x86_64-apple-darwin": "sha384-XiEz/V1PSnyyLRE+gfLVYaXfqz2wxyAvnLnAcenkYMVyjTyqEiOt+4KV0XLAIntk",
        "i386-pc-windows": "sha384-nb6h4pvSAyRUYVFr/BJvLl1FzU0DihjUBF1pLTmWkbGCPa550RcFwezZ7cnMarL0",
        "x86_64-pc-windows": "sha384-xuAs9WbcaxyZ+dkAKlGMsweSx3bbVhAtGjRpzYXocQ5DEO1ExaNEAZjIITup9IHp"
    },
    "1.53.0": {
        "aarch64-unknown-linux": "sha384-DP4eUy8yV8HxD5iYlV4XfzI7aGw/uaZSFNjAMQGGFTngy+M87hFIb8sJVStDuc3H",
        "i386-unknown-linux": "sha384-ibqMXBq910PzmwHeWxBvouaJwayPtzRqy2Een3dfzJsVt5TLtJdNa99IwQkFfeK4",
        "x86_64-unknown-linux": "sha384-NHTa38qzG3vfbIkWdRtIbk5FxL+HwmfYUtJw0oh/CaHnKyW3lkvDc2RDb4DtxGx8",
        "aarch64-apple-darwin": "sha384-aQppIohqm7mrcYXc1dQCCsZ/kJ4v5LKvC6gjBstjs5QrXIvBCVM45/xe0gWd7oQ/",
        "x86_64-apple-darwin": "sha384-O37kLTvoJG+FwBbzLXeEn6fbe7usku1NBvzuhexzo7LaGsE6YxWu1zliiN3NyaN4",
        "i386-pc-windows": "sha384-MlseGklLOpOHsusw0kNDfp9dkOtWgt2Jb6hEAyM6VF9qVx3ELEOqamJcDoRf27YS",
        "x86_64-pc-windows": "sha384-I5NHmKs4Q+pqljYE4ZHT16/meEgQty98ilx8mlvOD9E1uPIZJ4dlQ4ZcmxQY/BdA"
    },
    "1.52.3": {
        "aarch64-unknown-linux": "sha384-Bw1VSogg9dNFuDOTsEQWBxrZf6diWf2sDoJ6RJv07rm7kWmK6RKwAWGcXw5nLw/7",
        "i386-unknown-linux": "sha384-ZNBe9vWn06kse+2Hh7TAwbUvpxjYIE/FhT7U+MiCzAvkzm+xbPbwN4PIW4mOTyZC",
        "x86_64-unknown-linux": "sha384-jVoFsNStQa0IyWWVPpZQhth4alY0Uv+zs/AoX1BnIb6tUeMOaKNU04lQxbiivqqz",
        "aarch64-apple-darwin": "sha384-eSdle/pulP8C89tNXaGxaVkuCTmxiJVERAFICL0bFYrmi3eqfoQMxt6P26VzpgGR",
        "x86_64-apple-darwin": "sha384-tYUB4COFvnRLvHkJdMUDS2TkUdtHglC9b/Kh5T2M12X8Q71+EaPAQW+VdCsZQPnV",
        "i386-pc-windows": "sha384-uh8X4qCwtsKl+OlP8XOs19Cy+car/9f6zbKKQ71osQ8uu7rAA/gyUMQko2I9CLxM",
        "x86_64-pc-windows": "sha384-9DIP/aGkBMn3Ed9k20cKbYl6w+nDBPHWmGZQyJgMivWy9HORZZrGKY+qm/rLgCVA"
    },
    "1.52.2": {
        "aarch64-unknown-linux": "sha384-SPsSdSm6+Jtq8dOMG5BVJnqDdAglBpD5MwPYPDqoCjAzg6+l/mbnw2nU0PLJmn0E",
        "i386-unknown-linux": "sha384-pYaX/9hfX/OAoAiQWe+62+mxW6rIupzupBIX/W3+cNbn7jYXhZ01I3t08GjbG5x8",
        "x86_64-unknown-linux": "sha384-Ny8CMos0eXYjcyXwnySz8JRTiG+x7M/raRqGLZbZ/1HxqcailVEBiB/Qg9Fo2E16",
        "aarch64-apple-darwin": "sha384-La3/GCKFmfe3gg3iHfSmKSU9CaVf7+bP6sMtvKTGsfjiAT5ai9jjlDhWwlOb+k0u",
        "x86_64-apple-darwin": "sha384-6jZ0r46oeodAciunBqrsHtFykRmEk0RyN8XoQ2XDJw/xMxYG6Zf6BKgiyEWq2NS8",
        "i386-pc-windows": "sha384-fy14jserRDHvNl2J3p7AZ1XrIpyqS9B3CQrRDMVnzNO4OoLLcrSI/3x26h1oLjFa",
        "x86_64-pc-windows": "sha384-1Km7Ob6GxM+RfA8k1scoXcphbxWySuMnRlb6cOMIdV8QAgLhbTF1fnH7nuKFr2zS"
    },
    "1.52.1": {
        "aarch64-unknown-linux": "sha384-XIvi0L00l6WXm7v3dGs8+PSms0kyuWdsQhJVnhdOEBZlYFXklPHV/8cTvJFwtrn6",
        "i386-unknown-linux": "sha384-Nox+RFigsa9iaQiVLedt7lV1wTc9CfAfqvUqJiWWun2Y1QjTpx74wQe7lJXJHHxv",
        "x86_64-unknown-linux": "sha384-+BMNO4832CH8qnxaHfqlTsKGImppwhtuippfTUyenw9hiLZwIz7yloc8dD5sYNZ8",
        "aarch64-apple-darwin": "sha384-VnYpCKoDAA1lEcUhaqQhfL5B9v7hqfNfL3Ruqrsj3FfUqJLiO48XUvKEp9P/3VKL",
        "x86_64-apple-darwin": "sha384-1UjDXqj468eIyKiINBY+1km4jXs7lP/aQPJYSiYgu8eFsV+g0NcnyWxRke4B0G3X",
        "i386-pc-windows": "sha384-zSNFWSykxcLxTn0gtCg/qEhSoSMo6HQiBMPsozi+vHZ0yyN/7t66IyHP0FL85ai2",
        "x86_64-pc-windows": "sha384-kIDk2H8ij0HUaHp47VTiTkS2N3X2Sgh9lhXPZsLL+QbKJ+WUN7vNjl2EOdfBS9D3"
    },
    "1.52.0": {
        "aarch64-unknown-linux": "sha384-7XU1P0+CBNZdHHk/cFlcYj1kJProon7HyHRhHcNlsn31Yh2G+GNvfWxbt8c5q1iv",
        "i386-unknown-linux": "sha384-v0bEu4hvhkVUxLqg75Nbu0PUkopej15e2WJGLWn/10ccNoie6X767gx9zi+ykyv7",
        "x86_64-unknown-linux": "sha384-T3XSa3qbJUtyPanMOsSngpbgWR7spQyb0JYwxycZxA5rL9gwNl1WxeG0/Rt0bGy5",
        "aarch64-apple-darwin": "sha384-Q3iavo1fFWNirOsubN+n68Hbeq7cNKsyK0HBfaHMLdFDD7sEv5WJn4zjH0MfFTIj",
        "x86_64-apple-darwin": "sha384-vGiVxvArfH5IhTWryi5Cr7x6XWMs1E+ZHsNbMSQTafi5gUgtU22qaexnWo/0+eWJ",
        "i386-pc-windows": "sha384-BmvNVTpDWsJTtSJozXesBlbEx9hTMH5YtFSXrqqeyTAnetOShhf/x8HE9I74ZOuI",
        "x86_64-pc-windows": "sha384-yV6W9lodbwtrMtDGo3OfgrRCJEPd0vaTwef760eB5MqxoGqwi10ryH9KhVuX8A7t"
    },
    "1.51.0": {
        "aarch64-unknown-linux": "sha384-FVQoxXNol37jDXcQaiAOKgmj0CeF4LdWw4Nf6NzD+pKx6ftba9gdt/1yk0j3pQMa",
        "i386-unknown-linux": "sha384-qJvAGYwxn7lQ4N8ofWU8koZ65eq5QHUqiycw4E4IORiMomvCjTAqfrnM863VoLCO",
        "x86_64-unknown-linux": "sha384-PZudmhZUie2h2jlo9LLbyfZ36JssSiNpwsJD1B0rklObn92FezWgjGTixGG2q34U",
        "aarch64-apple-darwin": "sha384-L5Q1Ps5DjHJVcFvCuTGdSaY6HGbgg0lAptDtUBwhd0PnR6v+oKuAUK4hOQGKXC+h",
        "x86_64-apple-darwin": "sha384-Q3oe40zofpikwQOIhqc01xh6FQGRlmS9k/AT3ib2ultm1pe3N3fyTVJTa69DfIZS",
        "i386-pc-windows": "sha384-MFpSibibRAdfypZqZvwl4wv0AlZPIrSYYwRG4MqEYFhySulSPCnOCVIRGIaQYe0M",
        "x86_64-pc-windows": "sha384-OueTD9vzqs5UR1ckR9swQqXw0g7Zc4g2SWDVmGiahBTw22VxDkFtrRuFniC1IIqS"
    },
    "1.50.1": {
        "aarch64-unknown-linux": "sha384-/rwgKEz3JBQ17pY6gBc4T2mD8tI4yyevQtSNr8OEhGR8hgyOoQYCKV7Tf/LFApIN",
        "i386-unknown-linux": "sha384-evAGjkRMjBjz4ugoNQu0q0tuATzUsMJiQQCOa7doLM2OjVRS0r6fLm4O7kgeG0yM",
        "x86_64-unknown-linux": "sha384-Q4m8O72kdYyYO6PXZUkDclCyOw8gwgsdc90ugcCzatrlYmOPHS+AfAAhVsNXxJxb",
        "aarch64-apple-darwin": "sha384-tSrNNr3DzbyO1+sundrZjlsBqlKWvQprONZlFEzju4UJ1TiGgoyk3F74oPyMhogr",
        "x86_64-apple-darwin": "sha384-756zG8InaABV6SZ5wWx7emIa+7Mu2fjDmtQKvFoSpbn5l4V0JsqXW0/Z0W0h8tJX",
        "i386-pc-windows": "sha384-wN/P/DwQXkmvy/uFWzKDWfjAWV58HtGXkp5iG4a4wKD6BqI0Qmj/haYJJnGsc74F",
        "x86_64-pc-windows": "sha384-kjZxOkyX8Llb6XAION+RtWHpln0RC/JOIZEd/MniflCiWOCIlDcbesgzg3YBfJ7J"
    },
    "1.50.0": {
        "aarch64-unknown-linux": "sha384-igkYup+P9e7/P3ptCO4w+dp9EC1TRvLTtj/rKtDKMu7Gf06Dl+K6PVuW8x0ZrZ8N",
        "i386-unknown-linux": "sha384-es9e5u37cMvdhQZNQlez6TJvpUvcMVAxkvjRkNcauCh4TuhOowG8TZnz6jo37RuM",
        "x86_64-unknown-linux": "sha384-e3DTprXhDYPNgPK/v+U7H0rQDj78puBaW5oLWAFTZkVMhATbXFHxDhBVXUk65jCb",
        "aarch64-apple-darwin": "sha384-7ranom/SRaIXyIDWR4Sd4czt3StC7fmtWPIcac0SGp5bJhMvY5ly8oyEfU9A3N/H",
        "x86_64-apple-darwin": "sha384-s8obWexFuC0CSiZKZTy1E/ctypBdaEauBWz31ZhX7B10qaGPhxPKh7h+lLZomdEe",
        "i386-pc-windows": "sha384-EVP47PeJW7fRTQhABLRgaq70bh3/IpKIkXEutN1SjRNgUzbfyv6+2d3ZJXns0+p4",
        "x86_64-pc-windows": "sha384-hw/f0O2mv4Wn8kAMKkhVO5n5eKUDMSOfwPfaOgTjzb5SCqSmGNMyfEeneuvU0xhf"
    },
    "1.49.11": {
        "aarch64-unknown-linux": "sha384-b7cGVch9RseVyqCIx17dyzWOho4Z7varz4hn++yLHJgRevJ7vgv7D6SJWwGXa/KN",
        "i386-unknown-linux": "sha384-yq21zAidITt/0N3c2zFVgH2KBp9no64Si0MMcADoOk5jGr5ev8rS0a8uCxTJLCSK",
        "x86_64-unknown-linux": "sha384-dqe4xHfZwVTFUqxuW27oAiBaf2dIgWiOF6DR2qQ96pFRJAktTbmrdqSbOVdCzAYW",
        "aarch64-apple-darwin": "sha384-TBVhoAkrjy8S8WWF6jHf/TzsyBfSnmrjBYxC5ZmHPDDWFF8528j9zoBcq3UhwstZ",
        "x86_64-apple-darwin": "sha384-2Fzh5R3YksUkxb31mrzk+cmeGZjEQP17G7isrrvWkiQjM+8NTlJSJ+Xdqu5L6Kzs",
        "i386-pc-windows": "sha384-lPRA7cbFRza0cQDhqo/xbrOaDjmNFL7wpfCN8ktQAAneUMDkBkiLUW0UXoxUgVIR",
        "x86_64-pc-windows": "sha384-RYiGembYufWmXLW4LxkNF5F2a9Ygv6ElMzBiH6F8IcRh8z4yIMRk9gEk0Ajwr3wX"
    },
    "1.49.10": {
        "i386-unknown-linux": "sha384-VYmi8uph21SU5HIwkPxKKKUL5KCPjuukCGPVekSVkULbXwnh2kWTNSXU5JVdwRuC",
        "x86_64-unknown-linux": "sha384-I4qRaG3cleanr9oLhA5OQFu1WmZq9oqayH8abnFd7Cpi0mgWc/AWsYtifbpRgvhj",
        "i386-pc-windows": "sha384-fTYU1Tme0vMDJb+H1lK2A8JOzJS1zNhnfTh05cAj7E5abBIb1nKo6jipQwb6eys2",
        "x86_64-pc-windows": "sha384-xdiGiAjQMKyWTU6SejTcj1E2SSmNkF2BMFfctmAY7MIVCzmnmfddAL6z0IB2H+OY"
    },
    "1.49.9": {
        "i386-unknown-linux": "sha384-ICdnncsOMKir8EVUQRZJ6TMsYipvC4pd6GYxCu8pp8xh1SAPt+OFlfIK1cay+KWX",
        "x86_64-unknown-linux": "sha384-rHn55vO9GglZ1sIYJaAsBsAmqrV/BfHy2cgYFAxaIbATDrnkbHfAjG2hnuaGZW+N",
        "x86_64-apple-darwin": "sha384-95P2L7zGMPQL7hL/D9Ub5F3Mn6xagDPd026WDRkOcGzLDnIojIzcpb9Uja6cHjap",
        "i386-pc-windows": "sha384-IgvSd/7Mxj9eJ6vn33TIGbCIdwdF5d3g9BtmYnxq9kbO1I6NmjkDCVXKVB7ooHeT",
        "x86_64-pc-windows": "sha384-zQFl1xR+qSTMEJnz+PLMtBKOlxS9rpdAUnyM0QAAXID7Y9FtQV66wgcVCQJitx3+"
    },
    "1.49.8": {
        "i386-unknown-linux": "sha384-S4VdUw5Ax+Xtd0zkKIQeFKas1tG/QWzquS98b6GZTtw1KWbj+o1puwfE/1Z1z5Ao",
        "x86_64-unknown-linux": "sha384-SMZu3Z0ogSVNWmPRsmiKha0GkZGHR+kX+BE18SgviuJ666oVvNpojhVIb0KES3PF",
        "x86_64-apple-darwin": "sha384-2czanYPSAdqZtNv/0xRbf+kFTrslhm2Icu7reTNzKf5Hdt7o26u0sRVp9A2LNHoS",
        "i386-pc-windows": "sha384-s9bUUsVbAlXoIyqD5Ixhi5Dh0vDVxHzY3SfRJlQiDJRWMS/ytoXMTTZ09ewgB0/E",
        "x86_64-pc-windows": "sha384-PytTPrZA6rTQwYeOTHEasPT89gCcbYqWJoUfqR5HlVPnHZhkb+DoVo6evW+iuFoD"
    },
    "1.49.7": {
        "i386-unknown-linux": "sha384-VtVabwzjWnQkAFFRyoer4be5JyWIJXUXs9dAAX/BVNzKdFI/Zrpu0jDFNK87nM6n",
        "x86_64-unknown-linux": "sha384-HqkQ74g98bPm/WjHtNBcHf2ponK48qPzolzQZRhaYzu/WfQ6xymM9VeunWDIaBJO",
        "x86_64-apple-darwin": "sha384-ExpaCxniuYXy1g/wHT9NetJ2EjbrL8S8ToazS1GD6UFKsYbEC6e1m4bbbk3DO2rs",
        "i386-pc-windows": "sha384-YP8apDCHGM3gUKxSYM3jGi1skUcmwIKTYyRSo9ZyAiXaJnOhklk2f07m1bxnWOp2",
        "x86_64-pc-windows": "sha384-TtU8EqPfa8MxIjMhZiH8VcoXMz3IWOUBbSCodQHzvMlOPOePBP5bC++VbYcJYAfP"
    },
    "1.49.6": {
        "i386-unknown-linux": "sha384-NHGb8vIGvC3jSyHGidDnK+1rJmplbMJyWD9Mxi0I1zKlACTO4SBowXftyvaFj3rZ",
        "x86_64-unknown-linux": "sha384-BZplR1eheEdVTgwl5cOlM/TrgS5ioqm0MRzfFT8dW3gQrZh8oJJRT8KbV++UC42m",
        "x86_64-apple-darwin": "sha384-ZOZIUpjUMJhyStiUGxOf55M2++BvyZWqlDMRZwNGI8veQqT3ZLO+mNgaszoXBsZt",
        "i386-pc-windows": "sha384-5ALCKsRAbB0nsSGV/UXkKyGFXlE99WL1jX8xE7Ywx5h/QzclnCfN5jEN4mEtGprY",
        "x86_64-pc-windows": "sha384-D37hFB75R0UO3HcdEnhvlkd7WCQ/xmuG7MMxlAHIQsJ6xnsiPCdGjxtKLff6P9in"
    },
    "1.49.5": {
        "i386-unknown-linux": "sha384-iVb53HoKXP1X1D0we6hjUVZxgAuupKt8ebffslJKIZfvCxmFqJ6XvOqEPKuEoNrt",
        "x86_64-unknown-linux": "sha384-5+chKKzMC+k6ooGAOJ5m4EtbZa9BgPm4dWWfopdFtw93dUcQ/jjmbgkWo1qKCvov",
        "x86_64-apple-darwin": "sha384-u+r4JVi19oa4vd6w2JItVzdNjwNRCDFfCq/Z5qojcxfHvUO3EYWSg8yL1Dceeo5G",
        "i386-pc-windows": "sha384-wfOrExAGjI71kNqvDvVl2ga0LZ49xFqfKvpOJa1ex+W0oGX/Y6pxcrwFNfsfwLwx",
        "x86_64-pc-windows": "sha384-FYBKSw06GluT2AE0PQDzysp8UeGBm9+x8qx64BhDZWd9vE9bIknlU6RE8Th5o1qi"
    },
    "1.49.4": {
        "i386-unknown-linux": "sha384-sgCDGQ54Ta5Dmxv+XDCN7mAhV7xV41gQqBkFlJb/IeICGjXTO57hN7jvqPXPpmrM",
        "x86_64-unknown-linux": "sha384-fmJlzlY7vesQTltLxq8nScDW71U5NTD44APsjC71WrybRY03JQg8aiUW1JpDcThy",
        "x86_64-apple-darwin": "sha384-KMwBFcCPHfXd3dOFjm+jOm2a/d+PUAJtF2z9Atx8pGylZyyf6tMUCXEC2WLmi2xb",
        "i386-pc-windows": "sha384-SHvQXDuLiISJbg/g/FSCw0TCH5NGwIoQbp7cn1ZO+p+2rghgF4WEv+5265eCBTz3",
        "x86_64-pc-windows": "sha384-RFEES2gSBpp9IRVzfeJWfN/Wy5BpIrr6a3MNvJUqdTNPKLt+kftu7oj6EmLtwDDH"
    },
    "1.49.3": {
        "i386-unknown-linux": "sha384-SdswCa7GVhyQN9En4d5TfLJvmdmdLlt787LyUlEkSrfdFq0XroKghN4eg3w9aDFt",
        "x86_64-unknown-linux": "sha384-noZQT08EpvNTVvTKq0Ey64GR33MLyrGxZSoqqltFujpUWSOReT/ZgXy/+rMS7V7m",
        "x86_64-apple-darwin": "sha384-txwJHO0Zg3jML6nthdhSYASJPpfUS5rB0vJe1GG+r9Wwxy8zc/Ogk6GLihsusi1P",
        "i386-pc-windows": "sha384-mFPKRjZAdY3RkeDdDExZFQryC9KGi7p77jCtx0ssImRzvhOaFkoJ0Uul19+k+jbE",
        "x86_64-pc-windows": "sha384-Y+dmB1OT1xu4rqKfWX0aSESeJMLoCGWlty8pGQGyP0vwrPsFNqn6EKGbAPouSpRH"
    },
    "1.49.2": {
        "i386-unknown-linux": "sha384-EFXsb6dLRJLOvwtsCfNuKr41BMVQFsseLhtnFgF0+074uGr2zuQg4k9XdDm/VuMq",
        "x86_64-unknown-linux": "sha384-1CDn7BxEOuVSTrgVvKy5B3dXCLlHptKcHFOZc9zEC49JB/K6yE+zJTSPCbqASB0G",
        "x86_64-apple-darwin": "sha384-VmCTvtqqia4n213aYPJ04b2GuhhkKjlhETDa2qVzEbBTJC+Pk3nJkRUXJVjGvCYF",
        "i386-pc-windows": "sha384-ru8qG0ZI5RQASLnZmvunVlHpNIKZWugM/2WedUsqscqB2PD1nofChpGZFFPMTndx",
        "x86_64-pc-windows": "sha384-Xr6QOjLf3Fh/Pk94GZ/5dwMEfOstLfQajmpKvC1w3KoAx2LkvWoBdgB0snK1CyoI"
    },
    "1.49.1": {
        "i386-unknown-linux": "sha384-urLAZu+lWds49RGg929erBJ+EAXmmWRwaOw6oWJ4eC2yyPqGi0Ll438+3DBXsdW/",
        "x86_64-unknown-linux": "sha384-o5lurzAlGM4COqTqcT01oOFh3n303JZ2dn2AMyu1Xr6dOGFHdB5PshEQC4MucjPc",
        "x86_64-apple-darwin": "sha384-ti40ikmyiSZsyJRmfaAZiGBbdInbuigDd/RqhHnoXRkZcGs3Aae7URkgEsIBrcd6",
        "i386-pc-windows": "sha384-4e9kIph29/LhJ6HWaWzxvU6gA4tqXwzfVkXoKJHkKmAEFveCtwIzUC6/fBJUbdHo",
        "x86_64-pc-windows": "sha384-kYyJYikG3AKmiL/n2G5WHSZ8/fBu/3rhXzazhtxeLe059AxlUrH7omxEFWJScmKa"
    },
    "1.49.0": {
        "i386-unknown-linux": "sha384-9uFSr/Xu9KkGLiBXTd5Ls+RA/WB0YFx/hQvT92b4pdepqeGJZTpRrTqyAWOW3eTW",
        "x86_64-unknown-linux": "sha384-uAEcFOJg4RYUovsVLkq3OjxVGxwCYUUZaWeEa0fDd4SVR8SMksL3Huj0gr6DeSIl",
        "x86_64-apple-darwin": "sha384-YPvRlIRPp/sWHzXkAQHiEGg42eFd2z5BhyEQJsty45ST5HyKhzcDg5i1tA5KYNlI",
        "i386-pc-windows": "sha384-jB+B1IioWUy8YmP/I8ZrH9CjD0vJAjfoB76VH5YI9qTmaGbs9LqgtC7Ysmdn5pGP",
        "x86_64-pc-windows": "sha384-5cVd/8+dUjcSThdhpkqDyf0pJOYja7UfQvYyiAIhzqQ2QGXYHJwec43wWVm9EWgN"
    },
    "1.48.0": {
        "i386-unknown-linux": "sha384-PO1JrOF8Zi+YgqD4UCuikCow86Mf4Rqj3T1tsZirv+SaVATRvwfdjh/JBnKicu9t",
        "x86_64-unknown-linux": "sha384-SehRUUC03aW8XHEkEpCzpcFRmylNodqYAXFXdNusQVn6HvZVpNrYVzkCTu3SHr6n",
        "x86_64-apple-darwin": "sha384-Of1s2QSNWDY+lZIqGTsDI8jC5sok+03E2qpHwzAV3tZH6JNOg8uxylRmJXEo5PM9",
        "i386-pc-windows": "sha384-wCdh1T91pROZlceS734d+XESntky40IupgDYzFV/Amu6viTWX0u+jG5FsvIeobSD",
        "x86_64-pc-windows": "sha384-umOpkqVBioOHrIC/8ppODPuiZacriJVcGc1akGEC3Qb5jpXhMoJdRTMbm40ul/B8"
    },
    "1.47.0": {
        "i386-unknown-linux": "sha384-n6a+x7/wyOXTjN8tpMK/AzjE2Un8dCnirsGTu3WGFD6CDbU73qyaTW1rIo+UGWv0",
        "x86_64-unknown-linux": "sha384-WPFM3ZDi00fU5YYEbWSJmoGWgYuqMmdkQkv8Y8XzGlsJz9eBuhHgesT+a0I+MpQJ",
        "x86_64-apple-darwin": "sha384-54slMpO7h9peUEiq9h82KE6ts3Re28CnUFDZa989DGvMWzNC44ouoEpUzfCxy/e0",
        "i386-pc-windows": "sha384-ne8qEGYFtUC8UnsyTi5Bs7FW9vHnfApjYfCGV5QSpV1FlQqU7dPJdSXU0QteRynj",
        "x86_64-pc-windows": "sha384-R+aTxPZWxjUeGkNSeRFxwWK0j0ju5JTavPdsSuaZDhbNRjTX/vGMN8pVeITXmf6A"
    },
    "1.46.0": {
        "i386-unknown-linux": "sha384-l+trl9Hl5QCWglBtF/7ne0x+0s6Z5/VxBlf5fn9vdXvr7nP+MipO3AB+cD+TsV75",
        "x86_64-unknown-linux": "sha384-gDOu9UAYDGZTh0IXlkLPyKpXJXZ6L7ztLaehXaEcUq0KzNpkoC+jWiXs2n6jLB+7",
        "x86_64-apple-darwin": "sha384-fmRp+waTthqa5ezshCKHnejS7Ai5ndwIiCniVK6//e/n099wOC5oPYQHcTKTjOqb",
        "i386-pc-windows": "sha384-gK/aTzcg4Cd75SFElwWXr3TbfXC7KUL9PXl8ghGpElr/Z2bXI0NbzBTk1HO50G5o",
        "x86_64-pc-windows": "sha384-QNi280JAflecnDpjk6/ADXHy3u5WVBC+MU/owJ49Xb/yGq4LNqcQ3KkdiL9JF55R"
    }
}