name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v6
    permissions:
      contents: write
    with:
      release_files: gzgz_rules_sass-*.tar.gz
      prerelease: false
